import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, BadgeCheck, Building2, ClipboardCheck, MapPin, MessageCircle, Navigation, Phone, Play } from "lucide-react";
import { professionals } from "@/lib/data";
import { findPublishedProfessional, organizationForProfessional, publicProfessionals } from "@/lib/public-directory";
import { podcastForProfessional } from "@/lib/podcasts";
import { pageMetadata } from "@/lib/seo";
import { ProfileShareButton } from "@/components/ProfileShareButton";
import { professionalRedirects, professionalRedirectTarget } from "@/lib/professional-redirects";
import { siteUrl } from "@/lib/seo";
import { ProfessionalImage } from "@/components/ProfessionalImage";
import { FavoriteButton } from "@/components/FavoriteButton";

function presentationProfession(name: string, profession: string) { if (/^Dra\.?\s/i.test(name) && profession === "Médico") return "Médica"; if (/^Dr\.?\s/i.test(name)) return profession; return ({ "Médico": "Medicina", "Psicólogo": "Psicologia", "Fonoaudiólogo": "Fonoaudiologia", "Enfermeiro": "Enfermagem", "Educador físico": "Educação Física" } as Record<string,string>)[profession] ?? profession; }
function completeRegistration(value:string){const clean=value.replace(/\s*·\s*[^·]*(a validar|aguardando validação|pendente|a confirmar)[^·]*/gi,"").trim();return /\d/.test(clean)?clean:""}
function e164(digits:string){const d=digits.replace(/^0+/,"");return d.length===10||d.length===11?`55${d}`:d}
function whatsappHref(value:string){const digits=value.replace(/\D/g,"");return digits.length<10?"":`https://wa.me/${digits.startsWith("55")?digits:`55${digits}`}`}
function usableService(value:string,specialty:string){return !/^(consulta|acompanhamento|atendimento|cuidado|saúde|consulta clínica)$/i.test(value.trim())&&value.toLocaleLowerCase("pt-BR")!==specialty.toLocaleLowerCase("pt-BR")}
export function generateStaticParams(){return publicProfessionals.length?[...publicProfessionals.map((professional)=>({slug:professional.slug})),...Object.keys(professionalRedirects).map((slug)=>({slug}))]:[{slug:"perfil-indisponivel"}]}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const redirectTarget=professionalRedirectTarget(slug);if(redirectTarget)return{title:"Perfil atualizado | Guia Saúde",description:"Este endereço foi atualizado no Guia Saúde.",alternates:{canonical:`${siteUrl}${redirectTarget}`},robots:{index:false,follow:true}};const item=await findPublishedProfessional(slug,professionals);if(!item)return pageMetadata("Profissional não encontrado","Perfil profissional não encontrado no Guia Saúde.",`/profissionais/${slug}`);return pageMetadata(`${item.name} — ${item.specialty}`,`${item.profession} em ${item.city}. Perfil informativo no Guia Saúde, sem agendamento online.`,`/profissionais/${slug}`)}

export default async function ProfessionalPage({params}:{params:Promise<{slug:string}>}){
 const{slug}=await params;const redirectTarget=professionalRedirectTarget(slug);if(redirectTarget)return <main className="shell" style={{padding:"5rem 1.5rem"}}><meta httpEquiv="refresh" content={`0; url=${redirectTarget}`}/><script dangerouslySetInnerHTML={{__html:`window.location.replace(${JSON.stringify(redirectTarget)});`}}/><h1>Endereço atualizado</h1><p>Você será direcionado para a página atual.</p><Link href={redirectTarget}>Continuar</Link></main>;
 const item=await findPublishedProfessional(slug,professionals);if(!item)notFound();const podcastEpisode=podcastForProfessional(item.slug,item.name);const publicRegistration=completeRegistration(item.registration);const publicSummary=/(a validar|aguardando validação|pendente|em revisão|a confirmar)/i.test(item.summary)?"":item.summary;const nameSkip=new Set(["da","de","do","dos","das","e"]);const initials=item.name.replace(/^(dr|dra|sr|sra)\.?\s+/i,"").split(/\s+/).filter((part)=>part&&!nameSkip.has(part.toLowerCase())).slice(0,2).map((part)=>part[0]).join("").toUpperCase();const locationOrganization=organizationForProfessional(item);const locationName=locationOrganization?.name??item.organization;const locationAddress=locationOrganization?.address&&!/endere[cç]o\s+(aguardando validação|a validar|a confirmar)/i.test(locationOrganization.address)?locationOrganization.address:"";const locationPhone=locationOrganization?.phone?.replace(/\D/g,"")??"";const locations=item.locations?.length?item.locations:locationName?[{name:locationName,address:locationAddress,phone:locationPhone,mapUrl:locationOrganization?.mapUrl}]:[];const visibleServices=item.services.filter((service)=>usableService(service,item.specialty));const visibleAudience=item.audience?.filter(Boolean)??[];const canonicalUrl=`https://guiasaude.app.br/profissionais/${item.slug}/`;const primaryLocation=locations[0];const primaryPhone=e164(primaryLocation?.phone?.replace(/\D/g,"")||locationPhone);const primaryMapHref=primaryLocation?.mapUrl||(primaryLocation?.address?`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${primaryLocation.name}, ${primaryLocation.address}, ${item.city}, MG`)}`:"");const primaryWhats=primaryLocation?.whatsapp?whatsappHref(primaryLocation.whatsapp):"";const hasRealPhoto=!!item.imageUrl&&!item.imageUrl.includes("/avatars/")&&!item.imageUrl.includes("/placeholders/");
 const isPhysician=/^m[eé]dic/i.test(item.profession);const structuredData={"@context":"https://schema.org","@graph":[{"@type":"ProfilePage","@id":`${canonicalUrl}#profilepage`,url:canonicalUrl,name:`${item.name} — ${item.specialty} em ${item.city}/MG`,mainEntity:{"@id":`${canonicalUrl}#professional`}},{"@type":isPhysician?"Physician":"Person","@id":`${canonicalUrl}#professional`,name:item.name,...(isPhysician?{medicalSpecialty:item.specialty}:{jobTitle:`${item.profession} — ${item.specialty}`}),...(hasRealPhoto?{image:`${siteUrl}${item.imageUrl}`}:{}),...(publicSummary?{description:publicSummary}:{}),...(primaryLocation?.address?{address:{"@type":"PostalAddress",streetAddress:primaryLocation.address,addressLocality:item.city,addressRegion:"MG",addressCountry:"BR"}}:{}),...(primaryPhone?{telephone:`+${primaryPhone}`}:{}),url:canonicalUrl},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Guia Saúde",item:siteUrl},{"@type":"ListItem",position:2,name:"Profissionais",item:`${siteUrl}/buscar/`},{"@type":"ListItem",position:3,name:item.name,item:canonicalUrl}]}]};
 return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structuredData).replace(/</g,"\\u003c")}}/><main className="profile-page-clean"><section className="profile-clean-wrap">
  <Link href={`/buscar?cidade=${encodeURIComponent(item.city)}`} className="profile-clean-back"><ArrowLeft size={18}/><span>Voltar para a busca</span></Link>
  <div className="profile-desk-grid"><div className="profile-desk-main">
  <article className="pcx-card">
   <div className="pcx-cover" aria-hidden="true"/>
   <div className={`pcx-avatar${hasRealPhoto?"":" pcx-avatar-initials"}`} aria-hidden="true">{hasRealPhoto?<ProfessionalImage src={item.imageUrl!} sizes="160px" eager fetchPriority="high"/>:<span>{initials}</span>}</div>
   <div className="pcx-identity">
    <p className="pcx-profession">{presentationProfession(item.name,item.profession)}</p>
    <h1>{item.name}{item.verified&&publicRegistration?<BadgeCheck className="pcx-verified" size={22} aria-label="Registro profissional conferido"/>:null}</h1>
    <div className="pcx-actions">
     {primaryWhats?<a className="pcx-action pcx-action-wa" href={primaryWhats} target="_blank" rel="noreferrer" aria-label="Conversar pelo WhatsApp"><MessageCircle size={18}/></a>:null}
     {primaryPhone?<a className="pcx-action" href={`tel:+${primaryPhone}`} aria-label="Ligar"><Phone size={18}/></a>:null}
     {primaryMapHref?<a className="pcx-action" href={primaryMapHref} target="_blank" rel="noopener noreferrer" aria-label="Como chegar"><Navigation size={18}/></a>:null}
     <FavoriteButton compact professional={{slug:item.slug,name:item.name,profession:item.profession,specialty:item.specialty,city:item.city,organization:item.organization,imageUrl:item.imageUrl}}/>
     <ProfileShareButton name={item.name} url={canonicalUrl}/>
    </div>
    <p className="pcx-specialty">{item.specialty}</p>
    {publicRegistration?<p className="pcx-registration"><ClipboardCheck size={14}/>{publicRegistration}</p>:null}
    <div className="pcx-chips"><span><MapPin size={14}/>{item.city}/MG</span>{primaryLocation?.name?<span><Building2 size={14}/>{primaryLocation.name}</span>:null}</div>
    {publicSummary?<p className="pcx-summary">{publicSummary}</p>:null}
    {primaryWhats||primaryPhone?<div className="pcx-cta">{primaryWhats?<a className="pcx-cta-primary" href={primaryWhats} target="_blank" rel="noreferrer"><MessageCircle size={18}/>Agendar pelo WhatsApp</a>:<a className="pcx-cta-primary" href={`tel:+${primaryPhone}`}><Phone size={18}/>Ligar para agendar</a>}</div>:null}
   </div>
  </article>
  <nav className="pcx-tabs" aria-label="Seções do perfil">{visibleServices.length?<a href="#atuacao">Atuação</a>:null}{item.education||visibleAudience.length||item.insuranceInfo?<a href="#sobre">Sobre</a>:null}{locations.length?<a href="#onde-atende">Onde atende</a>:null}{podcastEpisode?<a href="#podcast">Podcast</a>:null}</nav>
  <section className="profile-clean-details">
   {visibleServices.length?<article id="atuacao"><h2>Especialidades e áreas de atuação</h2><div className="profile-clean-services">{visibleServices.map((service)=><span key={service}>{service}</span>)}</div></article>:null}
   {item.education?<article id="sobre" className="profile-clean-note"><h2>Formação e experiência</h2><p>{item.education}</p></article>:null}
   {visibleAudience.length?<article id={item.education?undefined:"sobre"}><h2>Público atendido</h2><div className="profile-clean-services">{visibleAudience.map((audience)=><span key={audience}>{audience}</span>)}</div></article>:null}
   {item.insuranceInfo?<article id={item.education||visibleAudience.length?undefined:"sobre"} className="profile-clean-note"><h2>Convênios e formas de atendimento</h2><p>{item.insuranceInfo}</p></article>:null}
   {locations.length?<article id="onde-atende"><h2>{locations.length>1?"Locais de atendimento":"Local de atendimento"}</h2>{locations.map((location)=>{const linkedOrganization=organizationForProfessional({city:item.city,organization:location.name});const locationMapHref=location.mapUrl||(location.address?`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${location.name}, ${location.address}, ${item.city}, MG`)}`:"");return <div className="profile-clean-location" key={`${location.name}-${location.address??""}`}><Building2 size={20}/><div><strong>{linkedOrganization?<Link href={`/empresas/${linkedOrganization.slug}`}>{location.name}</Link>:location.name}</strong>{location.address?<span>{location.address}</span>:null}<span>{item.city}, Minas Gerais</span>{locationMapHref?<a href={locationMapHref} target="_blank" rel="noopener noreferrer">Ver localização</a>:null}{location.phone&&location.phone.replace(/\D/g,"").length>=10?<a className="profile-location-contact" href={`tel:+${e164(location.phone.replace(/\D/g,""))}`}>Ligar para {location.name}</a>:null}{location.whatsapp&&whatsappHref(location.whatsapp)?<a className="profile-location-contact" href={whatsappHref(location.whatsapp)} target="_blank" rel="noreferrer">WhatsApp de {location.name}</a>:null}</div></div>})}</article>:null}
   {podcastEpisode?<article id="podcast" className="profile-podcast"><div className="profile-podcast-icon"><Play size={20} fill="currentColor"/></div><div><span>Participação no Conexão Saúde</span><h2>{podcastEpisode.topic}</h2><p>{podcastEpisode.guest} · {podcastEpisode.role}</p></div><a href={podcastEpisode.episodeUrl||"/podcast"} target={podcastEpisode.episodeUrl?"_blank":undefined} rel={podcastEpisode.episodeUrl?"noreferrer":undefined}>Assistir ao podcast</a></article>:null}
  </section>
  <p className="profile-clean-source">Informações reunidas a partir de fontes públicas e canais profissionais. <Link href="/sobre#como-verificamos">Como verificamos as informações</Link></p>{item.confirmedAt?<p className="profile-clean-confirmed">Informações confirmadas em {item.confirmedAt}.</p>:null}
  </div><div className="profile-desk-rail"><div className="profile-desk-contact"><h2>Fale com o consultório</h2><div className="pdc-primary">{primaryWhats?<a className="pdc-wa" href={primaryWhats} target="_blank" rel="noreferrer"><MessageCircle size={18}/> WhatsApp</a>:null}{primaryPhone?<a className="pdc-call" href={`tel:+${primaryPhone}`}><Phone size={17}/> {primaryLocation?.phone||locationOrganization?.phone||"Ligar"}</a>:null}{primaryMapHref?<a className="pdc-route" href={primaryMapHref} target="_blank" rel="noopener noreferrer"><Navigation size={17}/> Como chegar</a>:null}</div><div className="pdc-secondary"><FavoriteButton professional={{slug:item.slug,name:item.name,profession:item.profession,specialty:item.specialty,city:item.city,organization:item.organization,imageUrl:item.imageUrl}}/><ProfileShareButton name={item.name} url={canonicalUrl}/></div></div>
  <section className="profile-clean-update"><div><h2>Atualize este perfil</h2><p>É este profissional ou representa o perfil? Solicite a atualização das informações.</p></div><div><Link href={`/inclusao?tipo=professional&perfil=${encodeURIComponent(item.slug)}&acao=atualizacao`}>Solicitar atualização</Link></div></section></div></div>
 </section></main>{(primaryWhats||primaryPhone||primaryMapHref)?<div className={`profile-fixed-bar${(((primaryWhats||primaryPhone)?1:0)+(primaryMapHref?1:0))===1?" is-single":""}`}>{primaryWhats?<a className="pfb-primary" href={primaryWhats} target="_blank" rel="noreferrer"><MessageCircle size={19}/> WhatsApp</a>:primaryPhone?<a className="pfb-primary" href={`tel:+${primaryPhone}`}><Phone size={19}/> Ligar</a>:null}{primaryMapHref?<a className="pfb-route" href={primaryMapHref} target="_blank" rel="noopener noreferrer"><Navigation size={19}/> Como chegar</a>:null}</div>:null}</>
}
