import Link from "next/link";
import { notFound } from "next/navigation";
import { AdSlot } from "@/components/AdSlot";
import { SiteFooter } from "@/components/SiteFooter";
import { SiteHeader } from "@/components/SiteHeader";
import { professionals } from "@/lib/data";

export default async function ProfessionalPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const item = professionals.find(profile => profile.slug === slug);
  if (!item) notFound();
  return <><SiteHeader /><main><section className="profile-hero profile-directory-hero"><div className="shell profile-directory-grid"><div className="profile-avatar profile-avatar-large">GS</div><div className="profile-heading"><Link href="/buscar" className="back-link">← Voltar para busca</Link><p className="eyebrow">Perfil profissional demonstrativo</p><h1>{item.name}</h1><div className="profile-pill-row"><span>{item.profession}</span><span>{item.specialty}</span><span>{item.city}</span></div><p className="profile-specialty">{item.summary}</p><span className={item.verified ? "status-pill verified" : "status-pill pending"}>{item.verified ? "Perfil verificado" : "Validação documental pendente"}</span></div><aside className="profile-contact-card"><small>CONTATO PROFISSIONAL</small><strong>{item.organization}</strong><p>{item.phone}</p><Link href={item.whatsapp === "#" ? `/profissionais/${item.slug}` : item.whatsapp} aria-disabled={item.whatsapp === "#"}>Ver dados de contato</Link><span>Portal informativo, sem agendamento online.</span></aside></div></section><section className="section shell profile-directory-content"><article><div className="profile-section-head"><p className="eyebrow">Atuação</p><h2>Serviços e informações do perfil</h2></div><div className="profile-service-pills">{item.services.map(service => <span key={service}>{service}</span>)}</div><div className="profile-info-grid"><section><small>Especialidade</small><strong>{item.specialty}</strong><p>Área declarada no cadastro demonstrativo.</p></section><section><small>Categoria</small><strong>{item.profession}</strong><p>Categoria profissional usada para filtros no guia.</p></section><section><small>Cidade</small><strong>{item.city}</strong><p>Município principal de atendimento informado.</p></section></div><h2>Local de atendimento</h2><div className="location-card profile-location"><strong>{item.organization}</strong><span>{item.city} · endereço profissional aguardando conferência</span><p>Antes da publicação definitiva, os dados de localização e contato passam por revisão editorial.</p></div></article><aside><div className="information-card profile-verification"><p className="eyebrow">Verificação</p><dl><div><dt>Registro</dt><dd>{item.registration}</dd></div><div><dt>Fonte</dt><dd>Cadastro demonstrativo</dd></div><div><dt>Revisão</dt><dd>Pendente</dd></div><div><dt>Publicidade</dt><dd>Nenhum destaque contratado</dd></div></dl><Link href="/admin">Ver fluxo de revisão</Link></div><div className="profile-disclaimer"><strong>Importante</strong><p>O Guia Saúde é um portal informativo. Não realiza triagem, diagnóstico, prescrição ou agendamento de consultas.</p></div></aside></section><div className="shell"><AdSlot code="PROFILE_CONTENT_END" /></div></main><SiteFooter /></>;
}
