"use client";

import { useCallback, useEffect, useState } from "react";

type Campaign = { id:number; advertiserName:string; name:string; positionCode:string; citySlug:string|null; startsAt:string; endsAt:string; destinationUrl:string; status:string };
const positions = ["DIRECTORY_TOP", "COMPANY_DIRECTORY_TOP", "PROFILE_CONTENT_END", "DEMONSTRACAO_COMERCIAL", "CITY_PIUMHI_TOP", "CITY_CAPITOLIO_TOP", "CITY_ARCOS_TOP", "CITY_CAMPO-BELO_TOP"];
const initial = {advertiserName:"", name:"", positionCode:"DIRECTORY_TOP", citySlug:"", startsAt:"", endsAt:"", destinationUrl:"https://", status:"draft"};

export function CampaignManager(){
  const [items,setItems]=useState<Campaign[]>([]);
  const [loading,setLoading]=useState(true);
  const [error,setError]=useState("");
  const [form,setForm]=useState(initial);
  const load=useCallback(async()=>{setLoading(true);setError("");const response=await fetch("/api/admin/campaigns");if(!response.ok){setItems([]);setError(response.status===401?"Entre com a conta autorizada para gerenciar campanhas.":"Não foi possível carregar campanhas.")}else{const data=await response.json();setItems(data.items)}setLoading(false)},[]);
  useEffect(()=>{let active=true;fetch("/api/admin/campaigns").then(async response=>({response,data:response.ok?await response.json():null})).then(({response,data})=>{if(!active)return;if(!response.ok){setError(response.status===401?"Entre com a conta autorizada para gerenciar campanhas.":"Não foi possível carregar campanhas.");setItems([])}else{setError("");setItems(data.items)}setLoading(false)});return()=>{active=false}},[]);
  async function submit(event:React.FormEvent){event.preventDefault();setError("");const response=await fetch("/api/admin/campaigns",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});if(!response.ok){setError("Não foi possível salvar a campanha.");return}setForm(initial);await load()}
  async function status(id:number,value:string){await fetch("/api/admin/campaigns",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status:value})});await load()}
  async function remove(id:number){if(!window.confirm("Excluir esta campanha?"))return;await fetch(`/api/admin/campaigns?id=${id}`,{method:"DELETE"});await load()}
  return <div className="cms campaign-admin"><div className="cms-layout"><section className="cms-list"><div className="cms-list-head"><div><small>MÍDIA PAGA</small><h2>Campanhas e banners</h2></div><span>{items.length} campanhas</span></div>{loading&&<p className="cms-empty">Carregando...</p>}{!loading&&!items.length&&<p className="cms-empty">Nenhuma campanha cadastrada.</p>}{items.map(item=><article key={item.id}><div><small>{item.status} · {item.positionCode}</small><h3>{item.name}</h3><p>{item.advertiserName}</p><p>{item.startsAt} → {item.endsAt}</p></div><div className="cms-actions"><select value={item.status} onChange={e=>status(item.id,e.target.value)}><option value="draft">Rascunho</option><option value="published">Publicado</option><option value="paused">Pausado</option><option value="archived">Arquivado</option></select><button onClick={()=>remove(item.id)}>Excluir</button></div></article>)}</section><form className="cms-form" onSubmit={submit}><p className="eyebrow">Nova campanha</p><h2>Cadastrar banner</h2><label>Anunciante<input required value={form.advertiserName} onChange={e=>setForm({...form,advertiserName:e.target.value})}/></label><label>Nome da campanha<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Posição<select value={form.positionCode} onChange={e=>setForm({...form,positionCode:e.target.value})}>{positions.map(item=><option key={item}>{item}</option>)}</select></label><label>Cidade relacionada<input value={form.citySlug} onChange={e=>setForm({...form,citySlug:e.target.value})} placeholder="piumhi, arcos..."/></label><label>Início<input type="datetime-local" value={form.startsAt} onChange={e=>setForm({...form,startsAt:e.target.value})}/></label><label>Fim<input type="datetime-local" value={form.endsAt} onChange={e=>setForm({...form,endsAt:e.target.value})}/></label><label>Link de destino<input required value={form.destinationUrl} onChange={e=>setForm({...form,destinationUrl:e.target.value})}/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="draft">Rascunho</option><option value="published">Publicar</option><option value="paused">Pausado</option></select></label>{error&&<p className="cms-error">{error}</p>}<button className="cms-submit" type="submit">Salvar campanha</button></form></div></div>
}
