"use client";

import { useCallback, useEffect, useState } from "react";

type Item = { id:number; type:string; title:string; summary:string|null; status:string; updatedAt:string };
const modules = [{id:"article",label:"Matérias"},{id:"podcast",label:"Podcast"},{id:"magazine",label:"Revista"},{id:"banner",label:"Banners"}];

export function ContentManager(){
  const [type,setType]=useState("article"); const [items,setItems]=useState<Item[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const [form,setForm]=useState({title:"",summary:"",body:"",citySlug:"",status:"draft"});
  const load=useCallback(async()=>{setLoading(true);setError("");const response=await fetch(`/api/admin/content?type=${type}`);if(!response.ok){setError(response.status===401?"Entre com a conta autorizada para gerenciar o conteúdo.":"Não foi possível carregar o banco.");setItems([])}else{const data=await response.json();setItems(data.items)}setLoading(false)},[type]);
  useEffect(()=>{let active=true;fetch(`/api/admin/content?type=${type}`).then(async response=>({response,data:response.ok?await response.json():null})).then(({response,data})=>{if(!active)return;if(!response.ok){setError(response.status===401?"Entre com a conta autorizada para gerenciar o conteúdo.":"Não foi possível carregar o banco.");setItems([])}else{setError("");setItems(data.items)}setLoading(false)});return()=>{active=false}},[type]);
  async function submit(event:React.FormEvent){event.preventDefault();setError("");const response=await fetch("/api/admin/content",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,type})});if(!response.ok){setError("Não foi possível salvar. Verifique os campos e tente novamente.");return}setForm({title:"",summary:"",body:"",citySlug:"",status:"draft"});await load()}
  async function status(id:number,value:string){await fetch("/api/admin/content",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status:value})});await load()}
  async function remove(id:number){if(!window.confirm("Excluir este conteúdo permanentemente?"))return;await fetch(`/api/admin/content?id=${id}`,{method:"DELETE"});await load()}
  return <div className="cms"><nav className="cms-tabs">{modules.map(module=><button key={module.id} className={type===module.id?"active":""} onClick={()=>{setLoading(true);setType(module.id)}}>{module.label}</button>)}</nav><div className="cms-layout"><section className="cms-list"><div className="cms-list-head"><div><small>CONTEÚDO SALVO</small><h2>{modules.find(x=>x.id===type)?.label}</h2></div><span>{items.length} itens</span></div>{loading&&<p className="cms-empty">Carregando...</p>}{!loading&&!items.length&&<p className="cms-empty">Nenhum conteúdo cadastrado neste módulo.</p>}{items.map(item=><article key={item.id}><div><small>{item.status}</small><h3>{item.title}</h3><p>{item.summary||"Sem resumo"}</p></div><div className="cms-actions"><select value={item.status} onChange={e=>status(item.id,e.target.value)}><option value="draft">Rascunho</option><option value="review">Em revisão</option><option value="published">Publicado</option></select><button onClick={()=>remove(item.id)}>Excluir</button></div></article>)}</section><form className="cms-form" onSubmit={submit}><p className="eyebrow">Novo conteúdo</p><h2>Criar {modules.find(x=>x.id===type)?.label.toLowerCase()}</h2><label>Título<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Resumo<textarea rows={3} value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})}/></label><label>Conteúdo ou observações<textarea rows={7} value={form.body} onChange={e=>setForm({...form,body:e.target.value})}/></label><label>Cidade relacionada<select value={form.citySlug} onChange={e=>setForm({...form,citySlug:e.target.value})}><option value="">Regional / todas</option><option value="piumhi">Piumhi</option><option value="capitolio">Capitólio</option><option value="pimenta">Pimenta</option><option value="arcos">Arcos</option><option value="campo-belo">Campo Belo</option><option value="bambui">Bambuí</option><option value="sao-roque-de-minas">São Roque de Minas</option></select></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="draft">Salvar como rascunho</option><option value="review">Enviar para revisão</option><option value="published">Publicar agora</option></select></label>{error&&<p className="cms-error">{error}</p>}<button className="cms-submit" type="submit">Salvar conteúdo</button></form></div></div>
}
