import Link from "next/link";
import { ArrowRight, BookOpen, Building2, Ear, FlaskConical, HeartPulse, MapPin, Pill, Podcast, Search, Stethoscope, UserRound } from "lucide-react";
import { ToothIcon } from "@/components/ProfessionIcon";
import { SiteFooter } from "@/components/SiteFooter";
import { SiteHeader } from "@/components/SiteHeader";
import { activeCities } from "@/lib/cities";
import { articleImage, articles, magazineEditions, organizations, podcasts, professionals } from "@/lib/data";
import { pageMetadata } from "@/lib/seo";

export const metadata = pageMetadata("Encontre atendimento de saúde perto de você", "Busque profissionais, empresas, especialidades e serviços de saúde no Centro-Oeste de Minas.", "/");

export default function Home() {
  const shortcuts = [
    { label: "Médicos", href: "/buscar?profissao=M%C3%A9dico&tipo=profissionais", icon: Stethoscope }, { label: "Dentistas", href: "/buscar?profissao=Dentista&tipo=profissionais", icon: ToothIcon }, { label: "Psicólogos", href: "/buscar?profissao=Psic%C3%B3logo&tipo=profissionais", icon: HeartPulse }, { label: "Clínicas", href: "/buscar?q=cl%C3%ADnica&tipo=empresas", icon: Building2 }, { label: "Farmácias", href: "/buscar?q=farm%C3%A1cia&tipo=empresas", icon: Pill }, { label: "Laboratórios", href: "/buscar?q=laborat%C3%B3rio&tipo=empresas", icon: FlaskConical },
  ];
  const categories = [
    { label: "Médicos", href: "/buscar?cidade=Piumhi&profissao=M%C3%A9dico&tipo=profissionais", icon: Stethoscope }, { label: "Dentistas", href: "/buscar?cidade=Piumhi&profissao=Dentista&tipo=profissionais", icon: ToothIcon }, { label: "Psicólogos", href: "/buscar?cidade=Piumhi&profissao=Psic%C3%B3logo&tipo=profissionais", icon: HeartPulse }, { label: "Fisioterapeutas", href: "/buscar?cidade=Piumhi&profissao=Fisioterapeuta&tipo=profissionais", icon: UserRound }, { label: "Clínicas", href: "/buscar?cidade=Piumhi&q=cl%C3%ADnica&tipo=empresas", icon: Building2 }, { label: "Laboratórios", href: "/buscar?cidade=Piumhi&q=laborat%C3%B3rio&tipo=empresas", icon: FlaskConical }, { label: "Farmácias", href: "/buscar?cidade=Piumhi&q=farm%C3%A1cia&tipo=empresas", icon: Pill }, { label: "Outros serviços", href: "/buscar?cidade=Piumhi&tipo=empresas", icon: Building2 },
  ];
  const latestEpisode = podcasts[0];
  const featuredEdition = magazineEditions.find((edition) => edition.featured) ?? magazineEditions[0];
  const readableEdition = magazineEditions.find((edition) => edition.coverUrl) ?? featuredEdition;
  const latestArticle = articles.find((article) => article.slug === "radiologia-odontologica-diagnostico") ?? articles[0];
  const secondaryArticles = articles.filter((article) => article.slug !== latestArticle.slug).slice(0, 2);
  const availableCities = activeCities;
  const featuredProfessionals = professionals.filter((item) => item.city === "Piumhi" && item.name !== "Perfil demonstrativo").slice(0, 3);
  const featuredService = organizations.find((item) => item.city === "Piumhi" && /cl[íi]nica|hospital|laborat/i.test(item.category)) ?? organizations.find((item) => item.city === "Piumhi");

  return <><SiteHeader /><main>
    <section className="home-human-hero"><div className="shell home-human-hero-grid"><div className="home-human-copy"><p className="eyebrow">Guia Saúde · Centro-Oeste de Minas</p><h1>Saúde e cuidado perto de você.</h1><p>Encontre profissionais, clínicas, exames, serviços e informações de saúde na sua região.</p><form action="/buscar" className="home-human-search"><label><Search size={18} /><span>O que você procura?</span><input name="q" aria-label="O que você procura?" placeholder="Especialidade, profissional, clínica, exame ou serviço" /></label><label><MapPin size={17} /><select name="cidade" required defaultValue=""><option value="" disabled>Escolha sua cidade</option>{availableCities.map((city) => <option key={city.slug} value={city.name}>{city.name}</option>)}</select></label><button type="submit">Buscar <ArrowRight size={16} /></button></form><nav className="home-human-shortcuts" aria-label="Buscas rápidas">{shortcuts.map(({ label, href, icon: Icon }) => <Link key={label} href={href}><Icon size={16} />{label}</Link>)}</nav></div><div className="home-human-art" role="img" aria-label="Profissional de saúde acolhendo pessoas em um ambiente tranquilo"><span className="home-art-note home-art-note-profile">Informação local para cuidar melhor de você.</span><span className="home-art-note home-art-note-city"><MapPin size={14}/> Centro-Oeste de Minas</span></div></div></section>
    <section className="home-trust"><div className="shell home-trust-grid">{[[Stethoscope,"Profissionais de saúde","Informações para encontrar o cuidado certo."],[Building2,"Clínicas e consultórios","Serviços disponíveis na sua cidade."],[FlaskConical,"Exames e serviços","Busque pelo que precisa, com clareza."],[BookOpen,"Conteúdo regional","Informação para cuidar melhor."]].map(([Icon,title,text]) => { const ItemIcon = Icon as typeof Stethoscope; return <article key={title as string}><ItemIcon size={22}/><div><strong>{title as string}</strong><p>{text as string}</p></div></article> })}</div></section>
    <section className="home-city-choice"><div className="shell"><div className="home-section-head"><p className="eyebrow">Saúde na sua região</p><h2>Encontre atendimento perto de você</h2></div><div className="home-city-card"><div className="home-city-image" role="img" aria-label="Vista de Piumhi, Minas Gerais"/><div><p className="eyebrow">Disponível agora</p><h3>Piumhi – MG</h3><p>Profissionais, clínicas, serviços e conteúdos locais em um só lugar.</p><div className="home-city-actions"><Link href="/cidades/piumhi">Acessar Guia Saúde Piumhi <ArrowRight size={15}/></Link><Link href="/buscar?cidade=Piumhi">Buscar atendimento</Link></div></div></div></div></section>
    <section className="shell home-categories"><div className="home-section-head"><p className="eyebrow">Comece por aqui</p><h2>Do que você precisa hoje?</h2><p>Escolha uma categoria para iniciar sua busca.</p></div><nav className="home-category-grid" aria-label="Categorias de atendimento">{categories.map(({label,href,icon:Icon}) => <Link key={label} href={href}><Icon size={22}/><span>{label}</span><ArrowRight size={15}/></Link>)}</nav></section>
    <section className="shell home-guidance"><div className="home-guidance-head"><p className="eyebrow">Um caminho mais claro</p><h2>Cuidar da saúde pode ser mais simples.</h2></div><div className="home-guidance-grid">{[["Escolha sua cidade", "Encontre informações e serviços disponíveis na sua região."], ["Busque o atendimento ideal", "Pesquise por profissional, especialidade, clínica, exame ou serviço."], ["Entre em contato", "Veja localização e formas de atendimento disponíveis no perfil."]].map(([title,text], index) => <article key={title}><span className={`home-guidance-art art-${index + 1}`} aria-hidden="true"/><div><h3>{title}</h3><p>{text}</p></div></article>)}</div><Link href="/buscar?cidade=Piumhi" className="home-guidance-cta">Encontrar atendimento <ArrowRight size={15}/></Link></section>
    <section className="shell home-featured"><div className="home-featured-head"><div><p className="eyebrow">Piumhi</p><h2>Encontre atendimento em Piumhi</h2><p>Conheça alguns profissionais e serviços disponíveis na cidade.</p></div><Link href="/buscar?cidade=Piumhi">Ver todos em Piumhi <ArrowRight size={15}/></Link></div><div className="home-featured-grid">{featuredProfessionals.map((item) => <Link key={item.slug} href={`/profissionais/${item.slug}`} className="home-person-card"><span className="home-person-avatar" style={item.imageUrl ? {backgroundImage:`url(${item.imageUrl})`} : undefined}>{!item.imageUrl ? item.name.split(" ").filter((word)=>!/^dr(a)?\.?$/i.test(word)).slice(0,2).map((word)=>word[0]).join("") : null}</span><div><small>{item.profession}</small><strong>{item.name}</strong><p>{item.specialty}</p><em>{item.organization} · Piumhi</em></div><span className="home-card-cta">Conhecer profissional <ArrowRight size={14}/></span></Link>)}{featuredService ? <Link href={`/buscar?cidade=Piumhi&q=${encodeURIComponent(featuredService.name)}&tipo=empresas`} className="home-service-card"><span className="home-service-art"><Building2 size={28}/></span><small>{featuredService.category}</small><strong>{featuredService.name}</strong><p>{featuredService.address}</p><em>Ver detalhes <ArrowRight size={14}/></em></Link> : null}</div></section>
    <section className="shell home-editorial"><div className="home-section-head"><p className="eyebrow">Conteúdo do Guia Saúde</p><h2>Informação para cuidar melhor de você</h2></div><div className="home-editorial-grid"><article className="home-editorial-article" style={{backgroundImage:`linear-gradient(90deg,rgba(9,43,40,.86),rgba(9,43,40,.26)),url(${articleImage(latestArticle) ?? "/materias/radiologia-odontologica-diagnostico.jpg"})`}}><span>Artigo · {latestArticle.category}</span><h3>{latestArticle.title}</h3><p>{latestArticle.excerpt}</p><Link href={`/materias/${latestArticle.slug}`}>Ler matéria <ArrowRight size={14}/></Link></article><Link href="/podcast" className="home-editorial-podcast" style={{backgroundImage:`linear-gradient(0deg,rgba(11,61,57,.76),rgba(11,61,57,.04)),url(${latestEpisode.imageUrl})`}}><span><Podcast size={14}/> Podcast</span><strong>Conexão Saúde</strong><p>{latestEpisode.topic}</p><em>Ouvir episódio <ArrowRight size={14}/></em></Link><Link href={`/revista/${readableEdition.slug}`} className="home-editorial-magazine"><span><BookOpen size={14}/> Revista</span>{readableEdition.coverUrl ? <img src={readableEdition.coverUrl} alt={`Capa da ${readableEdition.number} edição da Guia Saúde`} /> : <div className="home-magazine-placeholder">guia saúde</div>}<div><strong>{readableEdition.number} edição</strong><p>{readableEdition.title}</p><em>Folhear revista <ArrowRight size={14}/></em></div></Link>{secondaryArticles.map((article) => <Link key={article.slug} href={`/materias/${article.slug}`} className="home-editorial-mini"><span>Artigo · {article.category}</span><strong>{article.title}</strong><p>{article.excerpt}</p><em>Ler conteúdo <ArrowRight size={13}/></em></Link>)}</div><Link className="home-editorial-all" href="/materias">Ver todos os conteúdos <ArrowRight size={15}/></Link></section>
    <section className="home-commercial"><div className="shell home-commercial-inner"><div><p className="eyebrow">Para profissionais e empresas</p><h2>Faça parte do Guia Saúde da sua região</h2><p>Apresente seus serviços, fortaleça sua presença local e ajude mais pessoas a encontrar atendimento.</p></div><div className="home-commercial-actions"><Link href="/inclusao">Cadastrar meu negócio <ArrowRight size={15}/></Link><Link href="/anuncie">Conhecer as soluções <ArrowRight size={15}/></Link></div></div></section>
  </main><SiteFooter /></>;
}
