import Link from "next/link";
import { ArrowRight, BookOpen, Building2, Headphones, MapPin, Search, ShieldCheck, Smartphone, Sparkles, Stethoscope } from "lucide-react";
import { FeaturedProfessionalsRotator } from "@/components/FeaturedProfessionalsRotator";
import { publishedProfessionals } from "@/lib/public-directory";
import { professionals } from "@/lib/data";
import { isFeaturedProfessional } from "@/lib/featured-professionals";

export async function DesktopHome(){
 const source=await publishedProfessionals(professionals);
 const featured=source.filter(i=>i.city==="Piumhi"&&isFeaturedProfessional(i.slug)).map(i=>({slug:i.slug,name:i.name,specialty:i.specialty,organization:i.organization,registration:i.registration,imageUrl:i.imageUrl}));
 return <main className="desktop-home">
  <section className="desktop-hero"><div className="desktop-hero-copy"><span className="desktop-eyebrow"><Sparkles size={15}/> GUIA SAÚDE · PIUMHI</span><h1>Sua saúde,<br/><em>mais perto de você.</em></h1><p>Encontre profissionais, clínicas e serviços da sua região em um só lugar — com informação confiável para cuidar melhor.</p><form className="desktop-search" action="/buscar"><input type="hidden" name="cidade" value="piumhi"/><Search size={20}/><input name="q" aria-label="Buscar" placeholder="Profissional, especialidade ou serviço"/><span><MapPin size={16}/> Piumhi · MG</span><button type="submit">Buscar <ArrowRight size={17}/></button></form><div className="desktop-hero-actions"><Link href="/buscar?cidade=piumhi">Explorar o Guia <ArrowRight size={16}/></Link><a href="#aplicativo">Conhecer o aplicativo</a></div><div className="desktop-trust"><span><ShieldCheck size={15}/> Diretório regional verificado</span><span>149 profissionais</span><span>68 estabelecimentos</span></div></div>
  <div className="desktop-phone-stage" aria-label="Prévia do aplicativo Guia Saúde"><div className="desktop-glow"/><div className="desktop-phone desktop-phone-back"><div className="desktop-phone-screen"><small>GUIA SAÚDE</small><h3>Conteúdos</h3><div className="desktop-mini-search"/><div className="desktop-mini-story"/><div className="desktop-mini-row"/><div className="desktop-mini-row short"/></div></div><div className="desktop-phone desktop-phone-front"><div className="desktop-phone-screen"><div className="desktop-mini-location"><MapPin size={12}/> Piumhi · MG</div><small>Olá!</small><h3>Como podemos<br/><em>cuidar de você</em> hoje?</h3><div className="desktop-mini-search"><Search size={14}/> Buscar no Guia Saúde</div><div className="desktop-mini-icons"><i/><i/><i/><i/></div><div className="desktop-mini-banner"><span>GUIA SAÚDE</span><b>Saúde mais perto de você</b></div></div></div></div></section>
  <section className="desktop-section desktop-discovery"><div className="desktop-section-title"><span>ENCONTRE O QUE PRECISA</span><h2>Saúde local, sem complicação.</h2><p>Comece por uma categoria ou pesquise diretamente pelo que você precisa.</p></div><div className="desktop-category-grid"><Link href="/buscar?cidade=piumhi&tipo=professionals"><Stethoscope/><div><strong>Profissionais</strong><small>Médicos e especialistas</small></div><ArrowRight/></Link><Link href="/buscar?cidade=piumhi&tipo=services&categoria=clinicas"><Building2/><div><strong>Clínicas e serviços</strong><small>Atendimento perto de você</small></div><ArrowRight/></Link><Link href="/materias"><BookOpen/><div><strong>Conteúdos</strong><small>Informação para cuidar melhor</small></div><ArrowRight/></Link><Link href="/podcast"><Headphones/><div><strong>Podcast</strong><small>Conversas sobre saúde</small></div><ArrowRight/></Link></div></section>
  <section className="desktop-section desktop-featured"><div className="desktop-section-head"><div><span>SELEÇÃO GUIA SAÚDE</span><h2>Profissionais em destaque</h2></div><Link href="/profissionais-destaque">Ver todos <ArrowRight size={15}/></Link></div><div className="desktop-professionals"><FeaturedProfessionalsRotator professionals={featured}/></div></section>
  <section className="desktop-editorial"><div className="desktop-editorial-copy"><span>CONTEÚDO GUIA SAÚDE</span><h2>Informação também é cuidado.</h2><p>Matérias, entrevistas, podcast e a Revista Guia Saúde reunidos em uma experiência editorial feita para a região.</p><Link href="/materias">Explorar conteúdos <ArrowRight size={16}/></Link></div><div className="desktop-editorial-cards"><Link href="/materias"><BookOpen/><small>MATÉRIAS</small><strong>Conteúdo para decisões mais informadas.</strong><ArrowRight/></Link><Link href="/podcast"><Headphones/><small>PODCAST</small><strong>Conversas com quem entende de saúde.</strong><ArrowRight/></Link><Link href="/revista"><Sparkles/><small>REVISTA</small><strong>O Guia Saúde também para folhear.</strong><ArrowRight/></Link></div></section>
  <section className="desktop-app" id="aplicativo"><div className="desktop-app-icon"><Smartphone size={31}/></div><div><span>GUIA SAÚDE NO SEU CELULAR</span><h2>Leve sua rede de saúde com você.</h2><p>Acesse profissionais, serviços, conteúdos, podcast e revista em uma experiência criada para o celular.</p><div className="desktop-store-buttons"><span>Em breve na<br/><b>App Store</b></span><span>Em breve no<br/><b>Google Play</b></span></div></div><div className="desktop-app-orb"/></section>
  <section className="desktop-business"><div><span>PARA PROFISSIONAIS E EMPRESAS</span><h2>Faça parte do Guia Saúde.</h2><p>Apresente seu trabalho para pessoas que estão procurando saúde e bem-estar na sua região.</p></div><Link href="/anuncie">Anuncie no Guia Saúde <ArrowRight size={16}/></Link></section>
 </main>;
}
