import Link from "next/link";
import { ArrowRight, BookOpen, Building2, Headphones, Heart, MapPin, Search, ShieldCheck, Smartphone, Sparkles, Stethoscope } from "lucide-react";
import { publishedProfessionals } from "@/lib/public-directory";
import { professionals } from "@/lib/data";
import { isFeaturedProfessional } from "@/lib/featured-professionals";

function AppleMark(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M17.05 12.54c-.03-3.07 2.5-4.56 2.61-4.63-1.43-2.09-3.66-2.37-4.45-2.4-1.9-.19-3.7 1.12-4.66 1.12-.96 0-2.45-1.09-4.02-1.06-2.07.03-3.98 1.2-5.04 3.05-2.15 3.73-.55 9.25 1.54 12.27 1.02 1.48 2.24 3.14 3.84 3.08 1.54-.06 2.12-.99 3.98-.99 1.86 0 2.38.99 4.01.96 1.65-.03 2.7-1.5 3.72-2.98 1.17-1.71 1.65-3.36 1.68-3.45-.04-.02-3.18-1.22-3.21-4.97ZM13.97 3.51C14.82 2.48 15.4 1.05 15.24-.38c-1.23.05-2.72.82-3.6 1.85-.79.91-1.48 2.36-1.29 3.75 1.37.11 2.77-.7 3.62-1.71Z"/></svg>}
function PlayMark(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M3.6 2.2a2 2 0 0 0-.5 1.35v16.9c0 .52.2 1 .52 1.35l9.52-9.8L3.6 2.2Zm10.72 10.99-2.4 2.47-7.45 7.67c.3.08.64.05.98-.14l11.77-6.68-2.9-3.32Zm4.2-2.38-2.98-1.69-2.48 2.55 2.5 2.56 2.96-1.68c.96-.55.96-1.19 0-1.74ZM4.48.67l7.47 7.68 2.39 2.46 2.89-3.32L5.45.81a1.43 1.43 0 0 0-.97-.14Z"/></svg>}

export async function DesktopHome(){
 const source=await publishedProfessionals(professionals);
 const featured=source.filter(i=>i.city==="Piumhi"&&isFeaturedProfessional(i.slug)).slice(0,6);
 return <main className="desktop-home">
  <header className="desktop-nav"><Link href="/" className="desktop-brand"><span>+</span><div><b>GUIA</b><strong>SAÚDE</strong></div></Link><nav><Link href="/buscar?cidade=piumhi&tipo=professionals">Profissionais</Link><Link href="/buscar?cidade=piumhi&tipo=services">Clínicas e serviços</Link><Link href="/materias">Conteúdos</Link><Link href="/podcast">Podcast</Link><Link href="/revista">Revista</Link><Link href="/anuncie">Anuncie</Link></nav><a className="desktop-download" href="#aplicativo"><Smartphone size={15}/> Baixar o app</a></header>
  <section className="desktop-hero"><div className="desktop-hero-copy"><span className="desktop-eyebrow"><Sparkles size={15}/> GUIA SAÚDE · PIUMHI</span><h1>Sua saúde,<br/><em>mais perto de você.</em></h1><p>Encontre profissionais, clínicas e serviços da sua região em um só lugar — com informação confiável para cuidar melhor.</p><form className="desktop-search" action="/buscar"><input type="hidden" name="cidade" value="piumhi"/><Search size={20}/><input name="q" aria-label="Buscar" placeholder="Profissional, especialidade ou serviço"/><span><MapPin size={16}/> Piumhi · MG</span><button type="submit">Buscar <ArrowRight size={17}/></button></form><div className="desktop-hero-actions"><Link href="/buscar?cidade=piumhi">Explorar o Guia <ArrowRight size={16}/></Link><a href="#aplicativo">Conhecer o aplicativo</a></div><div className="desktop-trust"><span><ShieldCheck size={15}/> Diretório regional verificado</span></div></div>
  <div className="desktop-phone-stage" aria-label="Prévia do aplicativo Guia Saúde"><div className="desktop-glow"/><div className="desktop-phone desktop-phone-back"><div className="desktop-phone-screen"><small>GUIA SAÚDE</small><h3>Conteúdos</h3><div className="desktop-mini-search"/><div className="desktop-mini-story"/><div className="desktop-mini-row"/><div className="desktop-mini-row short"/></div></div><div className="desktop-phone desktop-phone-front"><div className="desktop-phone-screen"><div className="desktop-mini-location"><MapPin size={12}/> Piumhi · MG</div><small>Olá!</small><h3>Como podemos<br/><em>cuidar de você</em> hoje?</h3><div className="desktop-mini-search"><Search size={14}/> Buscar no Guia Saúde</div><div className="desktop-mini-icons"><i/><i/><i/><i/></div><div className="desktop-mini-banner"><span>GUIA SAÚDE</span><b>Saúde mais perto de você</b></div></div></div></div></section>
  <section className="desktop-section desktop-discovery"><div className="desktop-section-title"><span>ENCONTRE O QUE PRECISA</span><h2>Saúde local, sem complicação.</h2><p>Comece por uma categoria ou pesquise diretamente pelo que você precisa.</p></div><div className="desktop-category-grid"><Link href="/buscar?cidade=piumhi&tipo=professionals"><Stethoscope/><div><strong>Profissionais</strong><small>Médicos e especialistas</small></div><ArrowRight/></Link><Link href="/buscar?cidade=piumhi&tipo=services&categoria=clinicas"><Building2/><div><strong>Clínicas e serviços</strong><small>Atendimento perto de você</small></div><ArrowRight/></Link><Link href="/materias"><BookOpen/><div><strong>Conteúdos</strong><small>Informação para cuidar melhor</small></div><ArrowRight/></Link><Link href="/podcast"><Headphones/><div><strong>Podcast</strong><small>Conversas sobre saúde</small></div><ArrowRight/></Link></div></section>
  <section className="desktop-section desktop-featured"><div className="desktop-section-head"><div><span>SELEÇÃO GUIA SAÚDE</span><h2>Profissionais em destaque</h2></div><Link href="/profissionais-destaque">Ver todos <ArrowRight size={15}/></Link></div><div className="desktop-pro-grid">{featured.map((p,index)=><Link className="desktop-pro-card" href={`/profissionais/${p.slug}`} key={p.slug}><div className="desktop-pro-photo">{p.imageUrl?<img src={p.imageUrl} alt={p.name}/>:<span>{p.name.split(" ").slice(0,2).map(x=>x[0]).join("")}</span>}<b>{String(index+1).padStart(2,"0")}</b></div><div className="desktop-pro-copy"><small>{p.specialty}</small><h3>{p.name}</h3>{p.registration&&<p>{p.registration}</p>}<div><span>{p.organization||"Atendimento em Piumhi"}</span><ArrowRight size={16}/></div></div></Link>)}</div></section>
  <section className="desktop-editorial"><div className="desktop-editorial-copy"><span>CONTEÚDO GUIA SAÚDE</span><h2>Informação também é cuidado.</h2><p>Matérias, entrevistas, podcast e a Revista Guia Saúde reunidos em uma experiência editorial feita para a região.</p><Link href="/materias">Explorar conteúdos <ArrowRight size={16}/></Link></div><div className="desktop-editorial-cards"><Link href="/materias"><BookOpen/><small>MATÉRIAS</small><strong>Conteúdo para decisões mais informadas.</strong><ArrowRight/></Link><Link href="/podcast"><Headphones/><small>PODCAST</small><strong>Conversas com quem entende de saúde.</strong><ArrowRight/></Link><Link href="/revista"><Sparkles/><small>REVISTA</small><strong>O Guia Saúde também para folhear.</strong><ArrowRight/></Link></div></section>
  <section className="desktop-app" id="aplicativo"><div className="desktop-app-copy"><span>GUIA SAÚDE NO SEU CELULAR</span><h2>Leve sua rede de saúde com você.</h2><p>Acesse profissionais, serviços, conteúdos, podcast e revista em uma experiência criada para o celular.</p><div className="desktop-app-benefits"><span><Heart size={14}/> Salve seus profissionais</span><span><Search size={14}/> Encontre serviços rapidamente</span><span><BookOpen size={14}/> Conteúdo sempre por perto</span></div><div className="desktop-store-buttons"><span><AppleMark/><span><small>Em breve na</small><b>App Store</b></span></span><span><PlayMark/><span><small>Em breve no</small><b>Google Play</b></span></span></div></div><div className="desktop-app-visual"><div className="desktop-app-orb"/><div className="desktop-app-phone"><div><small>GUIA SAÚDE</small><h3>Saúde perto<br/>de você.</h3><span className="desktop-app-search"><Search size={12}/> Buscar</span><i/><i/><i/></div></div><div className="desktop-app-badge"><ShieldCheck size={18}/><span><b>Informação local</b><small>na palma da mão</small></span></div></div></section>
  <section className="desktop-business"><div><span>PARA PROFISSIONAIS E EMPRESAS</span><h2>Faça parte do Guia Saúde.</h2><p>Apresente seu trabalho para pessoas que estão procurando saúde e bem-estar na sua região.</p></div><Link href="/anuncie">Anuncie no Guia Saúde <ArrowRight size={16}/></Link></section>
  <footer className="desktop-footer"><div className="desktop-footer-top"><Link href="/" className="desktop-brand desktop-brand-footer"><span>+</span><div><b>GUIA</b><strong>SAÚDE</strong></div></Link><p>Conectando pessoas à saúde da nossa região com informação, confiança e proximidade.</p><div className="desktop-footer-links"><div><b>Encontre</b><Link href="/buscar?cidade=piumhi&tipo=professionals">Profissionais</Link><Link href="/buscar?cidade=piumhi&tipo=services">Clínicas e serviços</Link></div><div><b>Conteúdo</b><Link href="/materias">Matérias</Link><Link href="/podcast">Podcast</Link><Link href="/revista">Revista</Link></div><div><b>Guia Saúde</b><Link href="/anuncie">Anuncie</Link><Link href="/sobre">Sobre</Link></div></div></div><div className="desktop-footer-bottom"><span>© 2026 Guia Saúde. Piumhi · MG</span><span>Saúde mais perto de você.</span></div></footer>
 </main>;
}
