"use client";

import Link from "next/link";
import { Archive, ArrowRight, BookOpen, Search } from "lucide-react";
import { type FormEvent, useState } from "react";

type Edition = { slug: string; number: string; year: string; title: string; description: string; coverUrl?: string; pdfUrl?: string; flipbook?: { dir: string; pages: number } };
const isDigital = (edition: Edition) => Boolean(edition.pdfUrl || edition.flipbook);
const launchIsFuture = true;

export function MagazineCatalog({ editions }: { editions: Edition[] }) {
  const current = editions.find(isDigital);
  const upcoming = editions.find((edition) => !isDigital(edition));
  const archive = editions.filter(isDigital);
  const [query, setQuery] = useState("");
  const [submittedQuery, setSubmittedQuery] = useState("");
  const [year, setYear] = useState("Todos os anos");
  const [order, setOrder] = useState("recent");
  const years = Array.from(new Set(archive.map((edition) => edition.year))).sort((a, b) => Number(b) - Number(a));
  const filteredEditions = archive.filter((edition) => (year === "Todos os anos" || edition.year === year) && (!submittedQuery || `${edition.number} ${edition.year} ${edition.title} ${edition.description}`.toLowerCase().includes(submittedQuery.toLowerCase()))).sort((a, b) => order === "recent" ? Number(b.year) - Number(a.year) : Number(a.year) - Number(b.year));
  function submit(event: FormEvent) { event.preventDefault(); setSubmittedQuery(query); }
  function reset() { setQuery(""); setSubmittedQuery(""); setYear("Todos os anos"); setOrder("recent"); }

  return <main className="magazine-library-page">
    <section className="magazine-library-hero"><div className="shell magazine-library-hero-grid"><div><p className="eyebrow">Revista Guia Saúde</p><h1>Histórias que circulam. Conteúdo que permanece.</h1><p>Há mais de uma década, a Revista Guia Saúde registra profissionais, histórias e avanços que fazem parte da saúde regional.</p><div className="magazine-hero-actions">{current && <Link href={`/revista/${current.slug}`}>Folhear edição mais recente <ArrowRight size={16} /></Link>}<a href="#acervo">Explorar o acervo <ArrowRight size={16} /></a></div></div>{current?.coverUrl && <div className="magazine-hero-cover-wrap"><span className="magazine-hero-page" /><img src={current.coverUrl} alt={`Capa da ${current.number} edição da Revista Guia Saúde, publicada em ${current.year}`} /><span>{current.number} edição · {current.year}</span><Link href={`/revista/${current.slug}`}>Folhear agora <ArrowRight size={14} /></Link></div>}</div></section>
    {current && <section className="shell magazine-current-info"><p className="eyebrow">Edição mais recente</p><div><div><h2>{current.title}</h2><p>Dra. Fernanda Mota compartilha sua visão sobre saúde ocular, prevenção e bem-estar na 13ª edição da Revista Guia Saúde.</p><span>{current.number} edição <b /> Publicada em {current.year} <b /> Piumhi <b /> Leitura digital</span></div><div><Link className="magazine-primary" href={`/revista/${current.slug}`}>Folhear edição <BookOpen size={16} /></Link><Link className="magazine-secondary" href={`/revista/${current.slug}#sumario`}>Ver detalhes <ArrowRight size={15} /></Link></div></div></section>}
    {upcoming && <section className="shell magazine-launch"><div className="magazine-launch-teaser"><span>14ª edição</span><strong>{launchIsFuture ? "Em produção" : "Publicação em breve"}</strong><small>Lançamento em 7 de novembro</small></div><div><p className="eyebrow">{launchIsFuture ? "Próximo lançamento" : "Publicação em breve"}</p><h2>A 14ª edição está chegando.</h2><p>Uma nova edição da Revista Guia Saúde está em produção. O lançamento será em 7 de novembro de 2026, durante a Festa dos Destaques Piumhienses.</p><strong>7 de novembro de 2026 · Piumhi</strong><Link href={`/revista/${upcoming.slug}`}>{launchIsFuture ? "Ver detalhes do lançamento" : "Ver detalhes da 14ª edição"} <ArrowRight size={15} /></Link></div></section>}
    <section id="acervo" className="shell magazine-archive-section"><form className="magazine-search" onSubmit={submit}><label><Search size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Busque por edição, ano, profissional ou tema" /></label><select value={year} onChange={(event) => setYear(event.target.value)}><option>Todos os anos</option>{years.map((option) => <option key={option}>{option}</option>)}</select><select value={order} onChange={(event) => setOrder(event.target.value)}><option value="recent">Mais recentes</option><option value="old">Mais antigas</option></select><button>Buscar <ArrowRight size={16} /></button></form><div className="magazine-archive-heading"><div><p className="eyebrow">Acervo</p><h2>Acervo digital</h2><p>Explore as edições digitalizadas da Revista Guia Saúde e acompanhe mais de uma década de histórias da saúde regional.</p></div><span>{archive.length} edições digitalizadas disponíveis</span></div><small className="magazine-archive-note">Este acervo reúne as edições atualmente digitalizadas e disponíveis para leitura.</small>{filteredEditions.length ? <div className="magazine-covers-grid">{filteredEditions.map((edition) => <Link key={edition.slug} href={`/revista/${edition.slug}`} className="magazine-cover-card">{edition.coverUrl ? <img src={edition.coverUrl} alt={`Capa da ${edition.number} edição da Revista Guia Saúde, ${edition.year}`} /> : <span>{edition.number}</span>}<div><small>{edition.number} edição · {edition.year}</small><h3>{edition.title}</h3><em>Folhear edição <ArrowRight size={14} /></em></div></Link>)}</div> : <div className="magazine-empty"><strong>Nenhuma edição encontrada</strong><p>Tente buscar por outro ano, profissional ou tema.</p><button onClick={reset}>Limpar busca</button></div>}</section>
    <section className="shell magazine-history"><div><p className="eyebrow">Nossa trajetória</p><h2>Uma história construída com a região.</h2><p>Desde 2013, a Revista Guia Saúde reúne profissionais, serviços, histórias e informações que acompanham a evolução da saúde em Piumhi.</p></div><ol><li><b>2013</b> Primeira edição</li><li><b>2022</b> Edição especial de 10 anos</li><li><b>2025</b> 13ª edição</li><li><b>2026</b> Próximo lançamento</li></ol></section>
    <section className="shell magazine-commercial"><div><p className="eyebrow">Para profissionais e marcas</p><h2>Sua história pode estar na próxima edição.</h2><p>Conheça oportunidades editoriais e publicitárias para profissionais, clínicas, empresas e marcas da área da saúde.</p></div><div><Link className="magazine-primary" href="/anuncie">Conhecer oportunidades <ArrowRight size={16} /></Link><Link className="magazine-secondary" href="/anuncie">Anunciar na revista <ArrowRight size={16} /></Link></div></section>
    <section className="shell magazine-continue"><h2>Continue explorando o Guia Saúde</h2><article><BookOpen size={22} /><div><strong>Matérias</strong><p>Leia conteúdos e orientações produzidos com profissionais da região.</p><Link href="/materias">Ver matérias <ArrowRight size={14} /></Link></div></article><article><Archive size={22} /><div><strong>Podcast</strong><p>Assista a conversas sobre saúde, prevenção e qualidade de vida.</p><Link href="/podcast">Ouvir o podcast <ArrowRight size={14} /></Link></div></article></section>
  </main>;
}
