"use client";
import Link from "next/link";
import { Archive, ArrowRight, BookOpen, Search } from "lucide-react";
import { FormEvent,useMemo,useState } from "react";
type E={slug:string;number:string;year:string;title:string;description:string;coverUrl?:string;pdfUrl?:string;flipbook?:{dir:string;pages:number}};const digital=(e:E)=>!!(e.pdfUrl||e.flipbook);
export function MagazineCatalog({editions}:{editions:E[]}){const current=editions.find(digital);const upcoming=editions.find(e=>!digital(e));const archive=editions.filter(digital);const[q,setQ]=useState("");const[s,setS]=useState("");const[y,setY]=useState("Todos os anos");const[o,setO]=useState("recent");const years=Array.from(new Set(archive.map(e=>e.year))).sort((a,b)=>+b-+a);const launchIsFuture=Date.now()<new Date(2026,10,7).getTime();const list=useMemo(()=>archive.filter(e=>(y==="Todos os anos"||e.year===y)&&(!s||`${e.number} ${e.year} ${e.title} ${e.description}`.toLowerCase().includes(s.toLowerCase()))).sort((a,b)=>o==="recent"?+b.year-+a.year:+a.year-+b.year),[archive,y,s,o]);const submit=(e:FormEvent)=>{e.preventDefault();setS(q)};const reset=()=>{setQ("");setS("");setY("Todos os anos");setO("recent")};return <main className="magazine-library-page">
<section className="magazine-library-hero"><div className="shell magazine-library-hero-grid"><div><p className="eyebrow">Revista Guia Saúde</p><h1>Histórias que circulam. Conteúdo que permanece.</h1><p>Há mais de uma década, a Revista Guia Saúde registra profissionais, histórias e avanços que fazem parte da saúde regional.</p><div className="magazine-hero-actions">{current&&<Link href={`/revista/${current.slug}`}>Folhear edição mais recente <ArrowRight size={16}/></Link>}<a href="#acervo">Explorar o acervo <ArrowRight size={16}/></a></div></div>{current?.coverUrl&&<div className="magazine-hero-cover-wrap"><span className="magazine-hero-page"/><img src={current.coverUrl} alt={`Capa da ${current.number} edição da Revista Guia Saúde, publicada em ${current.year}`}/><span>{current.number} edição · {current.year}</span><Link href={`/revista/${current.slug}`}>Folhear agora <ArrowRight size={14}/></Link></div>}</div></section>
{current&&<section className="shell magazine-current-info"><p className="eyebrow">Edição mais recente</p><div><div><h2>{current.title}</h2><p>Dra. Fernanda Mota compartilha sua visão sobre saúde ocular, prevenção e bem-estar na 13ª edição da Revista Guia Saúde.</p><span>{current.number} edição <b/> Publicada em {current.year} <b/> Piumhi <b/> Leitura digital</span></div><div><Link className="magazine-primary" href={`/revista/${current.slug}`}>Folhear edição <BookOpen size={16}/></Link><Link className="magazine-secondary" href={`/revista/${current.slug}#sumario`}>Ver detalhes <ArrowRight size={15}/></Link></div></div></section>}
{upcoming&&<section className="shell magazine-launch"><div className="magazine-launch-teaser"><span>14ª edição</span><strong>{launchIsFuture?"Em produção":"Publicação em breve"}</strong><small>Lançamento em 7 de novembro</small></div><div><p className="eyebrow">{launchIsFuture?"Próximo lançamento":"Publicação em breve"}</p><h2>A 14ª edição está chegando.</h2><p>Uma nova edição da Revista Guia Saúde está em produção. O lançamento será em 7 de novembro de 2026, durante a Festa dos Destaques Piumhienses.</p><strong>7 de novembro de 2026 · Piumhi</strong><Link href={`/revista/${upcoming.slug}`}>{launchIsFuture?"Ver detalhes do lançamento":"Ver detalhes da 14ª edição"} <ArrowRight size={15}/></Link></div></section>}
<section id="acervo" className="shell magazine-archive-section"><form className="magazine-search" onSubmit={submit}><label><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Busque por edição, ano, profissional ou tema"/></label><select value={y} onChange={e=>setY(e.target.value)}><option>Todos os anos</option>{years.map(x=><option key={x}>{x}</option>)}</select><select value={o} onChange={e=>setO(e.target.value)}><option value="recent">Mais recentes</option><option value="old">Mais antigas</option></select><button>Buscar <ArrowRight size={16}/></button></form><div className="magazine-archive-heading"><div><p className="eyebrow">Acervo</p><h2>Acervo digital</h2><p>Explore as edições digitalizadas da Revista Guia Saúde e acompanhe mais de uma década de histórias da saúde regional.</p></div><span>{archive.length} edições digitalizadas disponíveis</span></div><small className="magazine-archive-note">Este acervo reúne as edições atualmente digitalizadas e disponíveis para leitura.</small>{list.length?<div className="magazine-covers-grid">{list.map(e=><Link key={e.slug} href={`/revista/${e.slug}`} className="magazine-cover-card">{e.coverUrl?<img src={e.coverUrl} alt={`Capa da ${e.number} edição da Revista Guia Saúde, ${e.year}`}/>:<span>{e.number}</span>}<div><small>{e.number} edição · {e.year}</small><h3>{e.title}</h3><em>Folhear edição <ArrowRight size={14}/></em></div></Link>)}</div>:<div className="magazine-empty"><strong>Nenhuma edição encontrada</strong><p>Tente buscar por outro ano, profissional ou tema.</p><button onClick={reset}>Limpar busca</button></div>}</section>
<section className="shell magazine-history"><div><p className="eyebrow">Nossa trajetória</p><h2>Uma história construída com a região.</h2><p>Desde 2013, a Revista Guia Saúde reúne profissionais, serviços, histórias e informações que acompanham a evolução da saúde em Piumhi.</p></div><ol><li><b>2013</b> Primeira edição</li><li><b>2022</b> Edição especial de 10 anos</li><li><b>2025</b> 13ª edição</li><li><b>2026</b> Próximo lançamento</li></ol></section>
<section className="shell magazine-commercial"><div><p className="eyebrow">Para profissionais e marcas</p><h2>Sua história pode estar na próxima edição.</h2><p>Conheça oportunidades editoriais e publicitárias para profissionais, clínicas, empresas e marcas da área da saúde.</p></div><div><Link className="magazine-primary" href="/anuncie">Conhecer oportunidades <ArrowRight size={16}/></Link><Link className="magazine-secondary" href="/anuncie">Anunciar na revista <ArrowRight size={16}/></Link></div></section>
<section className="shell magazine-continue"><h2>Continue explorando o Guia Saúde</h2><article><BookOpen size={22}/><div><strong>Matérias</strong><p>Leia conteúdos e orientações produzidos com profissionais da região.</p><Link href="/materias">Ver matérias <ArrowRight size={14}/></Link></div></article><article><Archive size={22}/><div><strong>Podcast</strong><p>Assista a conversas sobre saúde, prevenção e qualidade de vida.</p><Link href="/podcast">Ouvir o podcast <ArrowRight size={14}/></Link></div></article></section></main>}
