"use client";

import Link from "next/link";
import { ArrowRight, BookOpen, Headphones, Search } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { HealthOSSectionHeader } from "@/components/HealthOSSectionHeader";

type EditorialArticle = { slug:string; category:string; title:string; excerpt:string; author?:string; authorRole?:string; date?:string; readingTime?:string; professionalSlug?:string; image?:string };
const topics=["Mais recentes","Prevenção","Saúde da mulher","Saúde infantil","Saúde bucal","Alimentação","Saúde mental","Pele","Cardiologia","Ortopedia","Oftalmologia","Bem-estar"];
function topicsFor(a:EditorialArticle){const c=`${a.category} ${a.title} ${a.excerpt}`.toLocaleLowerCase("pt-BR");const m:[string,RegExp][]=[["Prevenção",/preven|medicamento/],["Saúde da mulher",/mulher|gineco|gesta/],["Saúde infantil",/infância|infantil|pediatr/],["Saúde bucal",/bucal|odonto|implant/],["Alimentação",/alimenta|nutri/],["Saúde mental",/mental|vínculo|psican/],["Pele",/pele|dermat/],["Cardiologia",/cardio/],["Ortopedia",/ortoped|lesão/],["Oftalmologia",/oftalmo|olho|cirurgia refrativa/],["Bem-estar",/reabilita|vida saudável|respirat|qualidade de vida/]];return m.filter(([,r])=>r.test(c)).map(([t])=>t)}
function byline(a:EditorialArticle){if(!a.author||a.author==="Redação Guia Saúde")return a.readingTime?`Guia Saúde · ${a.readingTime}`:"Guia Saúde";return `${a.author}${a.authorRole?` · ${a.authorRole}`:""}${a.readingTime?` · ${a.readingTime}`:""}`}
function Img({article,featured=false}:{article:EditorialArticle;featured?:boolean}){return article.image?<div className={`content-native-image${featured?" is-featured":""}`} style={{backgroundImage:`url(${article.image})`}} role="img" aria-label={article.title}/>:<div className={`content-native-image fallback${featured?" is-featured":""}`}><BookOpen size={28}/></div>}
export function MateriasCatalog({articles,podcastImage,magazineCover,magazineSlug}:{articles:EditorialArticle[];podcastImage?:string;magazineCover?:string;magazineSlug?:string}){
 const [topic,setTopic]=useState("Mais recentes"),[query,setQuery]=useState(""),[submitted,setSubmitted]=useState(""),[count,setCount]=useState(8);
 const catalog=useMemo(()=>{const q=submitted.trim().toLocaleLowerCase("pt-BR");return articles.filter(a=>(topic==="Mais recentes"||topicsFor(a).includes(topic))&&(!q||`${a.title} ${a.excerpt} ${a.category} ${a.author??""}`.toLocaleLowerCase("pt-BR").includes(q)))},[articles,topic,submitted]);
 const feature=catalog[0], recent=catalog.slice(1,count+1); const search=(e:FormEvent)=>{e.preventDefault();setSubmitted(query);setCount(8)};
 return <main className="content-native-page"><section className="content-native-shell">
   <HealthOSSectionHeader eyebrow="GUIA SAÚDE" title="Conteúdos" description="Informação confiável para cuidar melhor." />
   <form className="content-native-search" onSubmit={search}><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Busque um tema ou especialidade" aria-label="Buscar conteúdos"/><button aria-label="Buscar"><ArrowRight size={18}/></button></form>
   <div className="content-native-topics">{topics.map(t=><button type="button" key={t} className={topic===t?"active":""} onClick={()=>{setTopic(t);setCount(8)}}>{t}</button>)}</div>
   {feature?<Link href={`/materias/${feature.slug}`} className="content-native-feature"><Img article={feature} featured/><div className="content-native-feature-copy"><span>{feature.category}</span><h2>{feature.title}</h2><p>{feature.excerpt}</p><small>{byline(feature)}</small><b>Ler matéria <ArrowRight size={14}/></b></div></Link>:<div className="content-native-empty"><strong>Nenhum conteúdo encontrado</strong><p>Tente outro tema ou categoria.</p></div>}
   {feature&&<><div className="content-native-heading"><div><span>ATUALIZAÇÕES</span><h2>Mais recentes</h2></div></div><div className="content-native-grid">{recent.map(a=><Link href={`/materias/${a.slug}`} className="content-native-card" key={a.slug}><Img article={a}/><div><span>{a.category}</span><h3>{a.title}</h3><small>{byline(a)}</small></div><ArrowRight className="content-native-card-arrow" size={16}/></Link>)}</div>{catalog.length>count+1&&<button className="content-native-more" type="button" onClick={()=>setCount(c=>c+6)}>Ver mais conteúdos <ArrowRight size={15}/></button>}</>}
   <div className="content-native-channels"><div className="content-native-heading"><div><span>EXPLORE</span><h2>Mais do Guia Saúde</h2></div></div><div className="content-native-channel-grid"><Link href="/podcast" className="content-native-channel">{podcastImage?<span style={{backgroundImage:`url(${podcastImage})`}}/>:<Headphones/>}<div><small>PODCAST</small><strong>Conversas sobre saúde</strong><b>Ouvir episódios <ArrowRight size={13}/></b></div></Link><Link href={magazineSlug?`/revista/${magazineSlug}`:"/revista"} className="content-native-channel">{magazineCover?<span style={{backgroundImage:`url(${magazineCover})`}}/>:<BookOpen/>}<div><small>REVISTA</small><strong>Leia a edição do Guia</strong><b>Abrir revista <ArrowRight size={13}/></b></div></Link></div></div>
 </section></main>
}
