"use client";

import Link from "next/link";
import { ArrowRight, ArrowUpRight, AtSign, ExternalLink, Headphones, Play, Search, Video, X } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";

type Episode = {
  slug: string; guest: string; role: string; topic: string; date: string; duration: string; status: string;
  imageUrl?: string; episodeUrl?: string; audioUrl?: string; professionalSlugs?: string[];
};

const months: Record<string, number> = { janeiro: 0, fevereiro: 1, março: 2, abril: 3, maio: 4, junho: 5, julho: 6, agosto: 7, setembro: 8, outubro: 9, novembro: 10, dezembro: 11 };
function parsed(value: string) { const match = value.toLowerCase().match(/(\d{1,2})\s+de\s+([a-zç]+)(?:\s+de\s+(\d{4}))?/); return match && months[match[2]] !== undefined ? new Date(Number(match[3] ?? 2026), months[match[2]], Number(match[1]), 12) : undefined; }
function date(value: string) { const result = parsed(value); return result ? new Intl.DateTimeFormat("pt-BR", { day: "numeric", month: "long", year: "numeric" }).format(result) : value; }
function status(episode: Episode) { if (episode.audioUrl || episode.episodeUrl || episode.status === "Disponível") return `Disponível · ${date(episode.date)}`; const result = parsed(episode.date); return result && result.getTime() > Date.now() ? `Próximo episódio · ${date(episode.date)}` : "Publicação em breve"; }
function tags(episode: Episode) { const source = `${episode.topic} ${episode.guest} ${episode.role}`.toLowerCase(); const categories: [string, RegExp][] = [["Saúde da mulher", /pélvica|gineco|mulher|harmonização/], ["Saúde bucal", /odonto|dent|implant|ortodont/], ["Saúde mental", /vínculo|mental|psicanal/], ["Nutrição", /nutri|aliment/], ["Fisioterapia", /fisioterap/], ["Oftalmologia", /oftalmo|blefaro|olhos|refrativa/], ["Dermatologia", /dermat|pele/], ["Ortopedia", /ortoped|lesão|regenerativa/], ["Endocrinologia", /endocrino|hormônio|metabolismo/]]; return categories.filter(([, expression]) => expression.test(source)).map(([label]) => label); }
function youtube(url?: string) { return url?.match(/[?&]v=([^&]+)/)?.[1]; }

function Cover({ episode }: { episode: Episode }) {
  return <span className="podcast-library-cover" style={episode.imageUrl ? { backgroundImage: `url(${episode.imageUrl})` } : undefined} role="img" aria-label={`Episódio com ${episode.guest}`}>{!episode.imageUrl ? <Headphones size={30} /> : null}</span>;
}

function EpisodePlayer({ episode, onClose }: { episode: Episode; onClose: () => void }) {
  const videoId = youtube(episode.episodeUrl);
  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); };
    document.body.classList.add("podcast-player-open"); window.addEventListener("keydown", onKeyDown);
    return () => { document.body.classList.remove("podcast-player-open"); window.removeEventListener("keydown", onKeyDown); };
  }, [onClose]);
  return <div className="podcast-player-backdrop" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onClose()}>
    <section className="podcast-player-sheet" role="dialog" aria-modal="true" aria-label={`Reproduzindo ${episode.topic}`}>
      <header><div><span>Reproduzindo agora</span><strong>Conexão Saúde</strong></div><button type="button" onClick={onClose} aria-label="Fechar player"><X size={20} /></button></header>
      <div className="podcast-player-media">
        {episode.audioUrl ? <div className="podcast-audio-player" style={episode.imageUrl ? { backgroundImage: `linear-gradient(135deg,rgba(5,47,43,.9),rgba(5,47,43,.48)),url(${episode.imageUrl})` } : undefined}><Headphones size={34} /><audio controls autoPlay preload="metadata" src={episode.audioUrl}>Seu dispositivo não oferece suporte ao player de áudio.</audio></div> : videoId ? <iframe src={`https://www.youtube-nocookie.com/embed/${videoId}?autoplay=1&playsinline=1&rel=0`} title={`Podcast Conexão Saúde: ${episode.topic}`} allow="autoplay; encrypted-media; picture-in-picture" allowFullScreen /> : <Cover episode={episode} />}
      </div>
      <div className="podcast-player-info"><small>{episode.audioUrl ? "Áudio" : "Vídeo dentro do app"}</small><h2>{episode.topic}</h2><p><strong>{episode.guest}</strong> · {episode.role}</p><div>{episode.professionalSlugs?.[0] ? <Link href={`/profissionais/${episode.professionalSlugs[0]}`} onClick={onClose}>Ver perfil <ArrowUpRight size={14} /></Link> : null}{episode.episodeUrl ? <a href={episode.episodeUrl} target="_blank" rel="noreferrer">Abrir no YouTube <ExternalLink size={14} /></a> : null}</div></div>
    </section>
  </div>;
}

export function PodcastCatalog({ episodes }: { episodes: Episode[] }) {
  const [q, setQ] = useState(""); const [search, setSearch] = useState(""); const [tag, setTag] = useState("Todos"); const [year, setYear] = useState("Todos"); const [visible, setVisible] = useState(9); const [playing, setPlaying] = useState<Episode | null>(null);
  const feature = episodes[0]; const categories = Array.from(new Set(episodes.flatMap(tags))); const years = Array.from(new Set(episodes.map((episode) => String(parsed(episode.date)?.getFullYear() ?? "")))).filter(Boolean).sort((a, b) => Number(b) - Number(a));
  const filtered = useMemo(() => episodes.filter((episode) => episode.slug !== feature?.slug && (tag === "Todos" || tags(episode).includes(tag)) && (year === "Todos" || String(parsed(episode.date)?.getFullYear()) === year) && (!search || `${episode.topic} ${episode.guest} ${episode.role}`.toLowerCase().includes(search.toLowerCase()))), [episodes, feature?.slug, tag, year, search]);
  const submit = (event: FormEvent) => { event.preventDefault(); setSearch(q); setVisible(9); }; const reset = () => { setQ(""); setSearch(""); setTag("Todos"); setYear("Todos"); setVisible(9); };
  return <main className="podcast-library-page">
    <section className="podcast-library-hero"><div className="shell podcast-library-hero-grid"><div><p className="eyebrow">Podcast Conexão Saúde</p><h1>Saúde para ouvir onde você estiver.</h1><p>Conversas com profissionais da região sobre prevenção, tratamentos e qualidade de vida.</p><div className="podcast-hero-meta" aria-label="Informações do podcast"><span><Headphones size={15} /> {episodes.length} episódios</span><span>Ouça dentro do app</span></div><div className="podcast-hero-actions"><a href="#episodios">Explorar episódios <ArrowRight size={16} /></a><Link href="/buscar">Conhecer profissionais <ArrowRight size={16} /></Link></div></div><div className="podcast-library-hero-art" style={feature?.imageUrl ? { backgroundImage: `linear-gradient(120deg,rgba(7,45,57,.9),rgba(7,45,57,.22)),url(${feature.imageUrl})` } : undefined}><span><Headphones size={22} /> conversas da nossa região</span></div></div></section>
    {feature ? <section className="shell podcast-latest"><article className="podcast-latest-card"><button className="podcast-latest-media podcast-media-button" type="button" onClick={() => setPlaying(feature)} aria-label={`Reproduzir ${feature.topic}`}><Cover episode={feature} /><i><Play size={22} fill="currentColor" /></i><span>Ouvir agora</span></button><div className="podcast-latest-copy"><p className="eyebrow">Episódio mais recente</p><h2>{feature.topic}</h2><strong>{feature.guest}</strong><span>{feature.role}</span><small>{status(feature)}{feature.duration ? ` · ${feature.duration}` : ""}</small><p>Uma conversa para informar, aproximar e ampliar o cuidado com temas presentes na comunidade.</p><div><button type="button" className="podcast-watch-btn" onClick={() => setPlaying(feature)}><Play size={15} fill="currentColor" /> Ouvir no app</button>{feature.professionalSlugs?.[0] ? <Link href={`/profissionais/${feature.professionalSlugs[0]}`} className="podcast-profile-button">Ver perfil do convidado <ArrowUpRight size={14} /></Link> : null}</div></div></article></section> : null}
    <section id="episodios" className="shell podcast-library-controls"><div className="podcast-controls-heading"><span>Encontre um episódio</span><small>Busque ou escolha um tema</small></div><form className="podcast-search" onSubmit={submit}><label><Search size={18} /><input value={q} onChange={(event) => setQ(event.target.value)} placeholder="Tema ou convidado" /></label><button aria-label="Buscar episódios">Buscar <ArrowRight size={16} /></button></form><div className="podcast-filter-row">{["Todos", ...categories].map((item) => <button type="button" key={item} className={tag === item ? "is-active" : ""} onClick={() => { setTag(item); setVisible(9); }}>{item}</button>)}</div>{years.length > 1 ? <div className="podcast-year-row"><span>Ano</span>{["Todos", ...years].map((item) => <button type="button" key={item} className={year === item ? "is-active" : ""} onClick={() => setYear(item)}>{item}</button>)}</div> : null}</section>
    <section className="shell podcast-library-listing"><div className="podcast-library-heading"><div><p className="eyebrow">Biblioteca</p><h2>Todos os episódios</h2><p>Escolha uma conversa e ouça sem sair do Guia Saúde.</p></div><span>{filtered.length} episódios</span></div>{filtered.length ? <div className="podcast-card-grid">{filtered.slice(0, visible).map((episode) => <article className="podcast-episode-card" key={episode.slug}><button className="podcast-episode-media podcast-media-button" type="button" onClick={() => setPlaying(episode)} aria-label={`Reproduzir ${episode.topic}`}><Cover episode={episode} /><i><Play size={16} fill="currentColor" /></i></button><div className="podcast-episode-copy"><small>{status(episode)}</small><h3>{episode.topic}</h3><p><b>{episode.guest}</b> · {episode.role}</p>{episode.duration ? <span>{episode.duration}</span> : null}<div>{episode.episodeUrl || episode.audioUrl ? <button type="button" onClick={() => setPlaying(episode)}><Play size={13} fill="currentColor" /> Ouvir no app</button> : null}{episode.professionalSlugs?.[0] ? <Link href={`/profissionais/${episode.professionalSlugs[0]}`}>Ver perfil <ArrowUpRight size={13} /></Link> : null}</div></div></article>)}</div> : <div className="podcast-empty"><strong>Nenhum episódio encontrado</strong><p>Tente buscar por outro tema, convidado ou especialidade.</p><button onClick={reset}>Limpar filtros</button></div>}{filtered.length > visible ? <button className="podcast-load-more" onClick={() => setVisible((value) => value + 6)}>Carregar mais episódios <ArrowRight size={16} /></button> : null}<div className="podcast-platforms"><strong>Assista e acompanhe</strong><a href="https://www.youtube.com/@redemeggabrasil" target="_blank" rel="noreferrer"><Video size={16} /> YouTube</a><a href="https://www.instagram.com/saudeguia" target="_blank" rel="noreferrer"><AtSign size={16} /> Instagram</a></div></section>
    {playing ? <EpisodePlayer episode={playing} onClose={() => setPlaying(null)} /> : null}
  </main>;
}
