"use client";

import Link from "next/link";
import { ArrowLeft, ArrowRight, ArrowUpRight, Headphones, Pause, Play, RotateCcw, RotateCw, Search, X } from "lucide-react";
import { FormEvent, useEffect, useMemo, useRef, useState } from "react";

type Episode={slug:string;guest:string;role:string;topic:string;date:string;duration:string;status:string;imageUrl?:string;episodeUrl?:string;audioUrl?:string;professionalSlugs?:string[]};
const months:Record<string,number>={janeiro:0,fevereiro:1,março:2,abril:3,maio:4,junho:5,julho:6,agosto:7,setembro:8,outubro:9,novembro:10,dezembro:11};
function parsed(value:string){const m=value.toLowerCase().match(/(\d{1,2})\s+de\s+([a-zç]+)(?:\s+de\s+(\d{4}))?/);return m&&months[m[2]]!==undefined?new Date(Number(m[3]??2026),months[m[2]],Number(m[1]),12):undefined}
function date(value:string){const result=parsed(value);return result?new Intl.DateTimeFormat("pt-BR",{day:"numeric",month:"short",year:"numeric"}).format(result):value}
function status(episode:Episode){if(episode.audioUrl||episode.episodeUrl||episode.status==="Disponível")return `Disponível · ${date(episode.date)}`;const result=parsed(episode.date);return result&&result.getTime()>Date.now()?`Próximo · ${date(episode.date)}`:"Em breve"}
function tags(episode:Episode){const source=`${episode.topic} ${episode.guest} ${episode.role}`.toLowerCase();const categories:[string,RegExp][]=[["Saúde da mulher",/pélvica|gineco|mulher|harmonização/],["Saúde bucal",/odonto|dent|implant|ortodont/],["Saúde mental",/vínculo|mental|psicanal/],["Nutrição",/nutri|aliment/],["Fisioterapia",/fisioterap/],["Oftalmologia",/oftalmo|blefaro|olhos|refrativa/],["Dermatologia",/dermat|pele/],["Ortopedia",/ortoped|lesão|regenerativa/],["Endocrinologia",/endocrino|hormônio|metabolismo/]];return categories.filter(([,r])=>r.test(source)).map(([label])=>label)}
function formatTime(value:number){if(!Number.isFinite(value))return"0:00";const m=Math.floor(value/60);const s=Math.floor(value%60);return`${m}:${String(s).padStart(2,"0")}`}
function Cover({episode}:{episode:Episode}){return <span className="hos-podcast-cover" style={episode.imageUrl?{backgroundImage:`url(${episode.imageUrl})`}:undefined}>{!episode.imageUrl?<Headphones size={28}/>:null}</span>}

function NativePlayer({episode,onClose}:{episode:Episode;onClose:()=>void}){
 const audioRef=useRef<HTMLAudioElement>(null);const[playing,setPlaying]=useState(false);const[current,setCurrent]=useState(0);const[duration,setDuration]=useState(0);
 useEffect(()=>{document.body.classList.add("podcast-player-open");return()=>document.body.classList.remove("podcast-player-open")},[]);
 const seek=(delta:number)=>{const audio=audioRef.current;if(audio){audio.currentTime=Math.max(0,Math.min(audio.duration||0,audio.currentTime+delta))}};
 const toggle=()=>{const audio=audioRef.current;if(!audio)return;if(audio.paused)void audio.play();else audio.pause()};
 return <div className="hos-player-backdrop" onMouseDown={(e)=>e.target===e.currentTarget&&onClose()}><section className="hos-player" role="dialog" aria-modal="true" aria-label={`Player: ${episode.topic}`}>
  <header><div><small>CONEXÃO SAÚDE</small><strong>Reproduzindo agora</strong></div><button onClick={onClose} aria-label="Fechar"><X size={18}/></button></header>
  <div className="hos-player-art"><Cover episode={episode}/><span className="hos-player-wave" aria-hidden="true"><i/><i/><i/><i/><i/><i/><i/></span></div>
  <div className="hos-player-copy"><h2>{episode.topic}</h2><p>{episode.guest} · {episode.role}</p></div>
  {episode.audioUrl?<><audio ref={audioRef} src={episode.audioUrl} preload="metadata" onLoadedMetadata={(e)=>setDuration(e.currentTarget.duration)} onTimeUpdate={(e)=>setCurrent(e.currentTarget.currentTime)} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>setPlaying(false)}/><div className="hos-player-progress"><input aria-label="Progresso do episódio" type="range" min="0" max={duration||0} step="1" value={Math.min(current,duration||0)} onChange={(e)=>{if(audioRef.current)audioRef.current.currentTime=Number(e.target.value)}}/><div><span>{formatTime(current)}</span><span>{formatTime(duration)}</span></div></div><div className="hos-player-controls"><button onClick={()=>seek(-15)} aria-label="Voltar 15 segundos"><RotateCcw size={19}/><small>15</small></button><button className="primary" onClick={toggle} aria-label={playing?"Pausar":"Reproduzir"}>{playing?<Pause size={25} fill="currentColor"/>:<Play size={25} fill="currentColor"/>}</button><button onClick={()=>seek(15)} aria-label="Avançar 15 segundos"><RotateCw size={19}/><small>15</small></button></div></>:<div className="hos-player-unavailable"><Headphones size={18}/><div><strong>Áudio no player do Guia Saúde</strong><p>Este episódio ainda não possui um arquivo de áudio próprio cadastrado. O app não incorpora o player do YouTube.</p></div></div>}
  {episode.professionalSlugs?.[0]?<Link className="hos-player-profile" href={`/profissionais/${episode.professionalSlugs[0]}`} onClick={onClose}>Ver perfil do convidado <ArrowUpRight size={14}/></Link>:null}
 </section></div>
}

export function PodcastCatalog({episodes}:{episodes:Episode[]}){
 const[q,setQ]=useState("");const[search,setSearch]=useState("");const[tag,setTag]=useState("Todos");const[visible,setVisible]=useState(8);const[playing,setPlaying]=useState<Episode|null>(null);const feature=episodes[0];const categories=Array.from(new Set(episodes.flatMap(tags)));
 const filtered=useMemo(()=>episodes.filter((episode)=>episode.slug!==feature?.slug&&(tag==="Todos"||tags(episode).includes(tag))&&(!search||`${episode.topic} ${episode.guest} ${episode.role}`.toLowerCase().includes(search.toLowerCase()))),[episodes,feature?.slug,tag,search]);
 const submit=(e:FormEvent)=>{e.preventDefault();setSearch(q);setVisible(8)};
 return <main className="hos-podcast-page"><section className="hos-podcast-shell">
  <header className="hos-podcast-header"><Link href="/" aria-label="Voltar"><ArrowLeft size={18}/></Link><div><small>GUIA SAÚDE</small><h1>Podcast</h1></div><span><Headphones size={18}/></span></header>
  <section className="hos-podcast-intro"><p>CONEXÃO SAÚDE</p><h2>Conversas que aproximam<br/><em>você do cuidado.</em></h2><span>Informação com profissionais da nossa região, para ouvir no seu tempo.</span></section>
  {feature?<article className="hos-podcast-feature"><button type="button" className="hos-podcast-feature-art" onClick={()=>setPlaying(feature)}><Cover episode={feature}/><i><Play size={21} fill="currentColor"/></i></button><div><small>EPISÓDIO EM DESTAQUE</small><h3>{feature.topic}</h3><p>{feature.guest} · {feature.role}</p><span>{status(feature)}{feature.duration?` · ${feature.duration}`:""}</span><button type="button" onClick={()=>setPlaying(feature)}><Play size={13} fill="currentColor"/> Ouvir no Guia Saúde</button></div></article>:null}
  <section className="hos-podcast-discover"><div className="hos-podcast-section-head"><div><small>BIBLIOTECA</small><h2>Explore os episódios</h2></div><span>{episodes.length} episódios</span></div><form onSubmit={submit} className="hos-podcast-search"><Search size={17}/><input value={q} onChange={(e)=>setQ(e.target.value)} placeholder="Tema ou convidado"/><button aria-label="Buscar"><ArrowRight size={16}/></button></form><div className="hos-podcast-chips">{["Todos",...categories].map((item)=><button type="button" key={item} className={tag===item?"active":""} onClick={()=>{setTag(item);setVisible(8)}}>{item}</button>)}</div></section>
  <section className="hos-podcast-list">{filtered.slice(0,visible).map((episode)=><article className="hos-podcast-row" key={episode.slug}><button className="hos-podcast-row-art" onClick={()=>setPlaying(episode)} aria-label={`Ouvir ${episode.topic}`}><Cover episode={episode}/><i><Play size={13} fill="currentColor"/></i></button><div><small>{status(episode)}</small><h3>{episode.topic}</h3><p>{episode.guest} · {episode.role}</p></div><button className="hos-podcast-row-play" onClick={()=>setPlaying(episode)} aria-label="Abrir player"><Play size={15} fill="currentColor"/></button></article>)}{filtered.length>visible?<button className="hos-podcast-more" onClick={()=>setVisible(v=>v+6)}>Ver mais episódios <ArrowRight size={14}/></button>:null}{!filtered.length?<div className="hos-podcast-empty"><Headphones size={24}/><strong>Nenhum episódio encontrado</strong><button onClick={()=>{setQ("");setSearch("");setTag("Todos")}}>Limpar busca</button></div>:null}</section>
 </section>{playing?<NativePlayer episode={playing} onClose={()=>setPlaying(null)}/>:null}</main>
}
