"use client";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, AtSign, Headphones, Play, Search, Video } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";

type Episode={slug:string;guest:string;role:string;topic:string;date:string;duration:string;status:string;imageUrl?:string;episodeUrl?:string;professionalSlugs?:string[]};
const months:Record<string,number>={janeiro:0,fevereiro:1,março:2,abril:3,maio:4,junho:5,julho:6,agosto:7,setembro:8,outubro:9,novembro:10,dezembro:11};
function parsed(value:string){const m=value.toLowerCase().match(/(\d{1,2})\s+de\s+([a-zç]+)(?:\s+de\s+(\d{4}))?/);return m&&months[m[2]]!==undefined?new Date(Number(m[3]??2026),months[m[2]],Number(m[1]),12):undefined}
function date(value:string){const d=parsed(value);return d?new Intl.DateTimeFormat("pt-BR",{day:"numeric",month:"long",year:"numeric"}).format(d):value}
function status(e:Episode){if(e.episodeUrl)return `Disponível · ${date(e.date)}`;const d=parsed(e.date);return d&&d>Date.now()?`Próximo episódio · ${date(e.date)}`:"Publicação em breve"}
function tags(e:Episode){const s=`${e.topic} ${e.guest} ${e.role}`.toLowerCase();const data:[string,RegExp][]=[["Saúde da mulher",/pélvica|gineco|mulher|harmonização/],["Saúde bucal",/odonto|dent|implant|ortodont/],["Saúde mental",/vínculo|mental|psicanal/],["Nutrição",/nutri|aliment/],["Fisioterapia",/fisioterap/],["Oftalmologia",/oftalmo|blefaro|olhos|refrativa/],["Dermatologia",/dermat|pele/],["Ortopedia",/ortoped|lesão|regenerativa/],["Endocrinologia",/endocrino|hormônio|metabolismo/]];return data.filter(([,r])=>r.test(s)).map(([x])=>x)}
function youtube(url?:string){return url?.match(/[?&]v=([^&]+)/)?.[1]}
function Cover({e}:{e:Episode}){return <span className="podcast-library-cover" style={e.imageUrl?{backgroundImage:`url(${e.imageUrl})`}:undefined} role="img" aria-label={`Episódio com ${e.guest}`}>{!e.imageUrl?<Headphones size={30}/>:null}</span>}

export function PodcastCatalog({episodes}:{episodes:Episode[]}){
 const [q,setQ]=useState("");const [search,setSearch]=useState("");const [tag,setTag]=useState("Todos");const [year,setYear]=useState("Todos");const [visible,setVisible]=useState(9);
 const feature=episodes.find(e=>e.episodeUrl)??episodes[0];const categories=Array.from(new Set(episodes.flatMap(tags)));const years=Array.from(new Set(episodes.map(e=>String(parsed(e.date)?.getFullYear()??"")))).filter(Boolean).sort((a,b)=>Number(b)-Number(a));
 const filtered=useMemo(()=>episodes.filter(e=>e.slug!==feature?.slug&&(tag==="Todos"||tags(e).includes(tag))&&(year==="Todos"||String(parsed(e.date)?.getFullYear())===year)&&(!search||`${e.topic} ${e.guest} ${e.role}`.toLowerCase().includes(search.toLowerCase()))),[episodes,feature?.slug,tag,year,search]);
 const submit=(ev:FormEvent)=>{ev.preventDefault();setSearch(q);setVisible(9)};const reset=()=>{setQ("");setSearch("");setTag("Todos");setYear("Todos");setVisible(9)};const id=youtube(feature?.episodeUrl);
 return <main className="podcast-library-page">
  <section className="podcast-library-hero"><div className="shell podcast-library-hero-grid"><div><p className="eyebrow">Podcast Conexão Saúde</p><h1>Conversas que informam e aproximam.</h1><p>Entrevistas com profissionais da região sobre saúde, prevenção, tratamentos, inovação e qualidade de vida.</p><div className="podcast-hero-actions"><a href="#episodios">Assistir episódios <ArrowRight size={16}/></a><Link href="/buscar">Conhecer o Guia Saúde <ArrowRight size={16}/></Link></div></div><div className="podcast-library-hero-art" style={feature?.imageUrl?{backgroundImage:`linear-gradient(120deg,rgba(7,45,57,.9),rgba(7,45,57,.22)),url(${feature.imageUrl})`}:undefined}><span><Headphones size={22}/> conversas da nossa região</span></div></div></section>
  {feature?<section className="shell podcast-latest"><article className="podcast-latest-card"><div className="podcast-latest-media">{id?<iframe src={`https://www.youtube-nocookie.com/embed/${id}`} title={`Podcast Conexão Saúde: ${feature.topic}`} loading="lazy" allowFullScreen/>:<Cover e={feature}/>}</div><div className="podcast-latest-copy"><p className="eyebrow">Episódio mais recente</p><h2>{feature.topic}</h2><strong>{feature.guest}</strong><span>{feature.role}</span><small>{status(feature)}{feature.duration?` · ${feature.duration}`:""}</small><p>Uma conversa do Conexão Saúde para informar, aproximar e ampliar o cuidado com temas presentes na comunidade.</p><div>{feature.episodeUrl?<a href={feature.episodeUrl} target="_blank" rel="noreferrer" className="podcast-watch-btn"><Play size={15} fill="currentColor"/> Assistir no YouTube</a>:null}{feature.professionalSlugs?.[0]?<Link href={`/profissionais/${feature.professionalSlugs[0]}`} className="podcast-profile-button">Ver perfil do convidado <ArrowUpRight size={14}/></Link>:null}</div></div></article></section>:null}
  <section id="episodios" className="shell podcast-library-controls"><form className="podcast-search" onSubmit={submit}><label><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Busque por tema ou convidado"/></label><button>Buscar <ArrowRight size={16}/></button></form><div className="podcast-filter-row">{["Todos",...categories].map(x=><button key={x} className={tag===x?"is-active":""} onClick={()=>{setTag(x);setVisible(9)}}>{x}</button>)}</div>{years.length>1?<div className="podcast-year-row"><span>Ano</span>{["Todos",...years].map(x=><button key={x} className={year===x?"is-active":""} onClick={()=>setYear(x)}>{x}</button>)}</div>:null}</section>
  <section className="shell podcast-library-listing"><div className="podcast-library-heading"><div><p className="eyebrow">Biblioteca</p><h2>Todos os episódios</h2><p>Explore conversas com profissionais da região sobre diferentes áreas da saúde.</p></div><span>{filtered.length} episódios</span></div>{filtered.length?<div className="podcast-card-grid">{filtered.slice(0,visible).map(e=><article className="podcast-episode-card" key={e.slug}><div className="podcast-episode-media">{e.episodeUrl?<a href={e.episodeUrl} target="_blank" rel="noreferrer"><Cover e={e}/><i><Play size={16} fill="currentColor"/></i></a>:<Cover e={e}/>}</div><div className="podcast-episode-copy"><small>{status(e)}</small><h3>{e.topic}</h3><p><b>{e.guest}</b> · {e.role}</p>{e.duration?<span>{e.duration}</span>:null}<div>{e.episodeUrl?<a href={e.episodeUrl} target="_blank" rel="noreferrer">Assistir episódio <ArrowRight size={13}/></a>:null}{e.professionalSlugs?.[0]?<Link href={`/profissionais/${e.professionalSlugs[0]}`}>Ver perfil do convidado <ArrowUpRight size={13}/></Link>:null}</div></div></article>)}</div>:<div className="podcast-empty"><strong>Nenhum episódio encontrado</strong><p>Tente buscar por outro tema, convidado ou especialidade.</p><button onClick={reset}>Limpar filtros</button></div>}{filtered.length>visible?<button className="podcast-load-more" onClick={()=>setVisible(v=>v+6)}>Carregar mais episódios <ArrowRight size={16}/></button>:null}<div className="podcast-platforms"><strong>Assista e acompanhe</strong><a href="https://www.youtube.com/@redemeggabrasil" target="_blank" rel="noreferrer"><Video size={16}/> YouTube</a><a href="https://www.instagram.com/saudeguia" target="_blank" rel="noreferrer"><AtSign size={16}/> Instagram</a></div></section>
 </main>
}
