export type Professional = {
  slug: string;
  name: string;
  profession: string;
  specialty: string;
  city: string;
  organization: string;
  registration: string;
  verified: boolean;
  summary: string;
  phone: string;
  whatsapp: string;
  services: string[];
  imageUrl?: string;
  coverImageUrl?: string;
  logoUrl?: string;
};

export type Organization = {
  slug: string;
  name: string;
  category: string;
  city: string;
  address: string;
  phone: string;
  summary: string;
  services: string[];
  logoUrl?: string;
  coverImageUrl?: string;
};

// Dados exclusivamente demonstrativos. Não representam pessoas reais.
const baseProfessionals: Professional[] = [
  {
    slug: "dra-helena-martins-cardiologia-piumhi",
    name: "Dra. Helena Martins",
    profession: "Médico",
    specialty: "Cardiologia",
    city: "Piumhi",
    organization: "Clínica Coração da Serra",
    registration: "CRM-MG 000000 · RQE 00000",
    verified: true,
    summary: "Cardiologista fictícia cadastrada para demonstração do portal. Perfil completo com apresentação profissional, áreas de atuação, local de atendimento, contato e imagens substituíveis.",
    phone: "(37) 99999-0000",
    whatsapp: "https://wa.me/5537999990000",
    services: ["Consulta cardiológica", "Check-up preventivo", "Hipertensão", "Risco cardiovascular", "Acompanhamento clínico"],
    imageUrl: "/placeholders/professional-photo.svg",
    coverImageUrl: "/placeholders/clinic-cover.svg",
    logoUrl: "/placeholders/company-logo.svg",
  },
  {
    slug: "perfil-demonstrativo-cardiologia-piumhi",
    name: "Perfil demonstrativo",
    profession: "Médico",
    specialty: "Cardiologia",
    city: "Piumhi",
    organization: "Clínica demonstrativa regional",
    registration: "CRM-MG · aguardando validação",
    verified: false,
    summary: "Exemplo de como serão apresentadas formação, atuação profissional, fontes e locais de atendimento.",
    phone: "Contato será validado",
    whatsapp: "#",
    services: ["Consulta cardiológica", "Avaliação preventiva", "Acompanhamento clínico"],
  },
  {
    slug: "perfil-demonstrativo-odontologia-capitolio",
    name: "Perfil demonstrativo",
    profession: "Dentista",
    specialty: "Odontologia geral",
    city: "Capitólio",
    organization: "Consultório demonstrativo",
    registration: "CRO-MG · aguardando validação",
    verified: false,
    summary: "Modelo de perfil para profissionais da odontologia e suas áreas declaradas de atendimento.",
    phone: "Contato será validado",
    whatsapp: "#",
    services: ["Avaliação odontológica", "Prevenção", "Saúde bucal"],
  },
  {
    slug: "perfil-demonstrativo-psicologia-arcos",
    name: "Perfil demonstrativo",
    profession: "Psicólogo",
    specialty: "Psicologia clínica",
    city: "Arcos",
    organization: "Espaço demonstrativo de saúde",
    registration: "CRP-MG · aguardando validação",
    verified: false,
    summary: "Modelo de apresentação de atendimento presencial ou online, abordagem e público atendido.",
    phone: "Contato será validado",
    whatsapp: "#",
    services: ["Atendimento individual", "Atendimento online", "Orientação psicológica"],
  },
  {
    slug: "perfil-demonstrativo-fisioterapia-campo-belo",
    name: "Perfil demonstrativo",
    profession: "Fisioterapeuta",
    specialty: "Fisioterapia",
    city: "Campo Belo",
    organization: "Centro demonstrativo de reabilitação",
    registration: "CREFITO · aguardando validação",
    verified: false,
    summary: "Exemplo para serviços de reabilitação, prevenção e acompanhamento fisioterapêutico.",
    phone: "Contato será validado",
    whatsapp: "#",
    services: ["Avaliação funcional", "Reabilitação", "Prevenção de lesões"],
  },
  {
    slug: "perfil-demonstrativo-nutricao-bambui",
    name: "Perfil demonstrativo",
    profession: "Nutricionista",
    specialty: "Nutrição clínica",
    city: "Bambuí",
    organization: "Clínica demonstrativa",
    registration: "CRN · aguardando validação",
    verified: false,
    summary: "Modelo para descrever áreas de atuação, público atendido e modalidades de consulta.",
    phone: "Contato será validado",
    whatsapp: "#",
    services: ["Avaliação nutricional", "Acompanhamento", "Educação alimentar"],
  },
  {
    slug: "perfil-demonstrativo-pediatria-pimenta",
    name: "Perfil demonstrativo",
    profession: "Médico",
    specialty: "Pediatria",
    city: "Pimenta",
    organization: "Consultório demonstrativo infantil",
    registration: "CRM-MG · aguardando validação",
    verified: false,
    summary: "Modelo para apresentar atendimento infantil, prevenção, acompanhamento de crescimento e orientação familiar.",
    phone: "Contato será validado",
    whatsapp: "#",
    services: ["Consulta pediátrica", "Puericultura", "Orientação preventiva"],
  },
  {
    slug: "perfil-demonstrativo-dermatologia-arcos",
    name: "Perfil demonstrativo",
    profession: "Médico",
    specialty: "Dermatologia",
    city: "Arcos",
    organization: "Clínica demonstrativa de pele",
    registration: "CRM-MG · aguardando validação",
    verified: false,
    summary: "Exemplo de perfil para áreas clínicas, procedimentos e acompanhamento dermatológico.",
    phone: "Contato será validado",
    whatsapp: "#",
    services: ["Avaliação dermatológica", "Prevenção", "Acompanhamento clínico"],
  },
  {
    slug: "perfil-demonstrativo-ortopedia-campo-belo",
    name: "Perfil demonstrativo",
    profession: "Médico",
    specialty: "Ortopedia",
    city: "Campo Belo",
    organization: "Centro demonstrativo de especialidades",
    registration: "CRM-MG · aguardando validação",
    verified: false,
    summary: "Modelo para apresentar avaliação de dores, lesões, acompanhamento e encaminhamentos.",
    phone: "Contato será validado",
    whatsapp: "#",
    services: ["Avaliação ortopédica", "Lesões esportivas", "Dor crônica"],
  },
  {
    slug: "perfil-demonstrativo-ginecologia-piumhi",
    name: "Perfil demonstrativo",
    profession: "Médico",
    specialty: "Ginecologia",
    city: "Piumhi",
    organization: "Espaço demonstrativo de saúde da mulher",
    registration: "CRM-MG · aguardando validação",
    verified: false,
    summary: "Exemplo de perfil para saúde da mulher, prevenção, acompanhamento e orientação clínica.",
    phone: "Contato será validado",
    whatsapp: "#",
    services: ["Consulta ginecológica", "Prevenção", "Saúde da mulher"],
  },
  {
    slug: "perfil-demonstrativo-endocrinologia-bambui",
    name: "Perfil demonstrativo",
    profession: "Médico",
    specialty: "Endocrinologia",
    city: "Bambuí",
    organization: "Clínica demonstrativa metabólica",
    registration: "CRM-MG · aguardando validação",
    verified: false,
    summary: "Modelo de perfil para cuidados metabólicos, diabetes, tireoide e acompanhamento longitudinal.",
    phone: "Contato será validado",
    whatsapp: "#",
    services: ["Diabetes", "Tireoide", "Acompanhamento metabólico"],
  },
  {
    slug: "perfil-demonstrativo-odontopediatria-pimenta",
    name: "Perfil demonstrativo",
    profession: "Dentista",
    specialty: "Odontopediatria",
    city: "Pimenta",
    organization: "Consultório demonstrativo odontológico",
    registration: "CRO-MG · aguardando validação",
    verified: false,
    summary: "Modelo para apresentar atendimento odontológico infantil e orientação preventiva para famílias.",
    phone: "Contato será validado",
    whatsapp: "#",
    services: ["Saúde bucal infantil", "Prevenção", "Acompanhamento"],
  },
  {
    slug: "perfil-demonstrativo-implantodontia-capitolio",
    name: "Perfil demonstrativo",
    profession: "Dentista",
    specialty: "Implantodontia",
    city: "Capitólio",
    organization: "Consultório demonstrativo de reabilitação oral",
    registration: "CRO-MG · aguardando validação",
    verified: false,
    summary: "Exemplo para perfis de reabilitação oral, implantes e planejamento odontológico.",
    phone: "Contato será validado",
    whatsapp: "#",
    services: ["Implantes", "Reabilitação oral", "Planejamento"],
  },
  {
    slug: "perfil-demonstrativo-fonoaudiologia-sao-roque",
    name: "Perfil demonstrativo",
    profession: "Fonoaudiólogo",
    specialty: "Fonoaudiologia",
    city: "São Roque de Minas",
    organization: "Espaço demonstrativo de terapias",
    registration: "CRFa · aguardando validação",
    verified: false,
    summary: "Modelo para apresentar avaliação, comunicação, voz, linguagem e acompanhamento terapêutico.",
    phone: "Contato será validado",
    whatsapp: "#",
    services: ["Avaliação fonoaudiológica", "Linguagem", "Voz"],
  },
  {
    slug: "perfil-demonstrativo-enfermagem-piumhi",
    name: "Perfil demonstrativo",
    profession: "Enfermeiro",
    specialty: "Enfermagem",
    city: "Piumhi",
    organization: "Serviço demonstrativo de cuidado",
    registration: "COREN-MG · aguardando validação",
    verified: false,
    summary: "Modelo para profissionais de enfermagem, orientação, prevenção e cuidados domiciliares quando aplicável.",
    phone: "Contato será validado",
    whatsapp: "#",
    services: ["Orientação em saúde", "Prevenção", "Cuidados domiciliares"],
  },
  {
    slug: "perfil-demonstrativo-odontologia-piumhi",
    name: "Perfil demonstrativo",
    profession: "Dentista",
    specialty: "Odontologia geral",
    city: "Piumhi",
    organization: "Consultório odontológico demonstrativo",
    registration: "CRO-MG · aguardando validação",
    verified: false,
    summary: "Modelo visual para futuros dentistas de Piumhi, com foto, serviços, registro e contato substituíveis após validação.",
    phone: "Contato será validado",
    whatsapp: "#",
    services: ["Avaliação odontológica", "Prevenção", "Saúde bucal"],
    imageUrl: "/placeholders/professional-photo.svg",
    coverImageUrl: "/placeholders/clinic-cover.svg",
  },
  {
    slug: "perfil-demonstrativo-psicologia-piumhi",
    name: "Perfil demonstrativo",
    profession: "Psicólogo",
    specialty: "Psicologia clínica",
    city: "Piumhi",
    organization: "Espaço terapêutico demonstrativo",
    registration: "CRP-MG · aguardando validação",
    verified: false,
    summary: "Modelo visual para psicólogos de Piumhi, mantendo dados sensíveis e identidade profissional pendentes de confirmação.",
    phone: "Contato será validado",
    whatsapp: "#",
    services: ["Atendimento individual", "Saúde mental", "Orientação psicológica"],
    imageUrl: "/placeholders/professional-photo.svg",
    coverImageUrl: "/placeholders/clinic-cover.svg",
  },
  {
    slug: "perfil-demonstrativo-fisioterapia-piumhi",
    name: "Perfil demonstrativo",
    profession: "Fisioterapeuta",
    specialty: "Fisioterapia",
    city: "Piumhi",
    organization: "Centro de reabilitação demonstrativo",
    registration: "CREFITO · aguardando validação",
    verified: false,
    summary: "Modelo visual para profissionais de fisioterapia, reabilitação, pilates e prevenção de lesões em Piumhi.",
    phone: "Contato será validado",
    whatsapp: "#",
    services: ["Reabilitação", "Pilates", "Avaliação funcional"],
    imageUrl: "/placeholders/professional-photo.svg",
    coverImageUrl: "/placeholders/clinic-cover.svg",
  },
  {
    slug: "perfil-demonstrativo-nutricao-piumhi",
    name: "Perfil demonstrativo",
    profession: "Nutricionista",
    specialty: "Nutrição clínica",
    city: "Piumhi",
    organization: "Consultório nutricional demonstrativo",
    registration: "CRN · aguardando validação",
    verified: false,
    summary: "Modelo visual para nutricionistas de Piumhi, com áreas, serviços e canais de contato prontos para substituição.",
    phone: "Contato será validado",
    whatsapp: "#",
    services: ["Avaliação nutricional", "Educação alimentar", "Acompanhamento"],
    imageUrl: "/placeholders/professional-photo.svg",
    coverImageUrl: "/placeholders/clinic-cover.svg",
  },
  {
    slug: "perfil-demonstrativo-pediatria-piumhi",
    name: "Perfil demonstrativo",
    profession: "Médico",
    specialty: "Pediatria",
    city: "Piumhi",
    organization: "Consultório infantil demonstrativo",
    registration: "CRM-MG · aguardando validação",
    verified: false,
    summary: "Modelo visual para pediatras de Piumhi, preparado para exibir formação, registro, local e contato após revisão.",
    phone: "Contato será validado",
    whatsapp: "#",
    services: ["Consulta pediátrica", "Puericultura", "Orientação preventiva"],
    imageUrl: "/placeholders/professional-photo.svg",
    coverImageUrl: "/placeholders/clinic-cover.svg",
  },
  {
    slug: "perfil-demonstrativo-educacao-fisica-arcos",
    name: "Perfil demonstrativo",
    profession: "Educador físico",
    specialty: "Atividade física e saúde",
    city: "Arcos",
    organization: "Studio demonstrativo de saúde",
    registration: "CREF · aguardando validação",
    verified: false,
    summary: "Exemplo para profissionais de atividade física, prevenção, condicionamento e qualidade de vida.",
    phone: "Contato será validado",
    whatsapp: "#",
    services: ["Treinamento personalizado", "Condicionamento", "Prevenção"],
  },
  {
    slug: "perfil-demonstrativo-farmacia-clinica-campo-belo",
    name: "Perfil demonstrativo",
    profession: "Farmacêutico",
    specialty: "Farmácia clínica",
    city: "Campo Belo",
    organization: "Serviço demonstrativo farmacêutico",
    registration: "CRF-MG · aguardando validação",
    verified: false,
    summary: "Modelo para orientação farmacêutica, acompanhamento e educação em saúde.",
    phone: "Contato será validado",
    whatsapp: "#",
    services: ["Orientação farmacêutica", "Educação em saúde", "Acompanhamento"],
  },
];

const supplementalProfessionals: Professional[] = [
  ...["Capitólio", "Pimenta", "Arcos", "Campo Belo", "Bambuí", "São Roque de Minas"].flatMap((city) => {
    const slugCity = city.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/\s+/g, "-");
    return [
      ["Médico", "Clínica médica", "CRM-MG", "Consulta clínica", "Prevenção", "Acompanhamento"],
      ["Dentista", "Odontologia geral", "CRO-MG", "Avaliação odontológica", "Prevenção", "Saúde bucal"],
      ["Psicólogo", "Psicologia clínica", "CRP-MG", "Atendimento individual", "Saúde mental", "Orientação"],
      ["Fisioterapeuta", "Fisioterapia", "CREFITO", "Reabilitação", "Pilates", "Avaliação funcional"],
      ["Nutricionista", "Nutrição clínica", "CRN", "Avaliação nutricional", "Educação alimentar", "Acompanhamento"],
      ["Médico", "Pediatria", "CRM-MG", "Consulta pediátrica", "Puericultura", "Orientação preventiva"],
    ].map(([profession, specialty, council, ...services]) => ({
      slug: `perfil-demonstrativo-${specialty.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/\s+/g, "-")}-${slugCity}`,
      name: "Perfil demonstrativo",
      profession,
      specialty,
      city,
      organization: `Serviço demonstrativo de ${city}`,
      registration: `${council} · aguardando validação`,
      verified: false,
      summary: `Modelo visual para futuros cadastros de ${specialty.toLowerCase()} em ${city}, com foto, registro, serviços e contato substituíveis após validação.`,
      phone: "Contato será validado",
      whatsapp: "#",
      services,
      imageUrl: "/placeholders/professional-photo.svg",
      coverImageUrl: "/placeholders/clinic-cover.svg",
    }));
  }),
];

export const professionals: Professional[] = [...baseProfessionals, ...supplementalProfessionals];

const baseOrganizations: Organization[] = [
  {
    slug: "clinica-demonstrativa-piumhi",
    name: "Clínica demonstrativa",
    category: "Clínica multiprofissional",
    city: "Piumhi",
    address: "Endereço profissional aguardando validação",
    phone: "Contato aguardando validação",
    summary: "Perfil demonstrativo de empresa, criado para validar a experiência antes da importação do CNES.",
    services: ["Consultas", "Atendimento multiprofissional", "Prevenção"],
  },
  {
    slug: "laboratorio-demonstrativo-arcos",
    name: "Laboratório demonstrativo",
    category: "Laboratório",
    city: "Arcos",
    address: "Endereço profissional aguardando validação",
    phone: "Contato aguardando validação",
    summary: "Modelo para estabelecimentos com unidades, horários, serviços e contatos comerciais.",
    services: ["Exames laboratoriais", "Coleta", "Atendimento regional"],
  },
  {
    slug: "farmacia-demonstrativa-capitolio",
    name: "Farmácia demonstrativa",
    category: "Farmácia",
    city: "Capitólio",
    address: "Endereço comercial aguardando validação",
    phone: "Contato aguardando validação",
    summary: "Modelo para farmácias e serviços de orientação ao público, com dados comerciais revisados.",
    services: ["Medicamentos", "Atenção farmacêutica", "Produtos de saúde"],
  },
  {
    slug: "otica-demonstrativa-pimenta",
    name: "Ótica demonstrativa",
    category: "Ótica",
    city: "Pimenta",
    address: "Endereço comercial aguardando validação",
    phone: "Contato aguardando validação",
    summary: "Exemplo de perfil para óticas, lentes, armações e serviços ligados à saúde visual.",
    services: ["Óculos", "Lentes", "Saúde visual"],
  },
  {
    slug: "clinica-estetica-demonstrativa-campo-belo",
    name: "Clínica estética demonstrativa",
    category: "Estética e bem-estar",
    city: "Campo Belo",
    address: "Endereço comercial aguardando validação",
    phone: "Contato aguardando validação",
    summary: "Modelo para empresas de estética, autocuidado, bem-estar e procedimentos não invasivos.",
    services: ["Estética facial", "Bem-estar", "Autocuidado"],
  },
  {
    slug: "academia-demonstrativa-bambui",
    name: "Academia demonstrativa",
    category: "Academia e atividade física",
    city: "Bambuí",
    address: "Endereço comercial aguardando validação",
    phone: "Contato aguardando validação",
    summary: "Perfil demonstrativo para espaços de atividade física, prevenção e qualidade de vida.",
    services: ["Musculação", "Aulas coletivas", "Condicionamento"],
  },
  {
    slug: "diagnostico-demonstrativo-piumhi",
    name: "Centro demonstrativo de diagnóstico",
    category: "Diagnóstico por imagem",
    city: "Piumhi",
    address: "Endereço comercial aguardando validação",
    phone: "Contato aguardando validação",
    summary: "Modelo para serviços de imagem, exames e apoio diagnóstico com dados de atendimento revisados.",
    services: ["Imagem", "Exames", "Apoio diagnóstico"],
  },
  {
    slug: "home-care-demonstrativo-sao-roque",
    name: "Home care demonstrativo",
    category: "Home care",
    city: "São Roque de Minas",
    address: "Atendimento local aguardando validação",
    phone: "Contato aguardando validação",
    summary: "Exemplo para empresas de cuidado domiciliar, acompanhamento e suporte familiar.",
    services: ["Cuidado domiciliar", "Acompanhamento", "Suporte familiar"],
  },
  {
    slug: "clinica-odontologica-demonstrativa-capitolio",
    name: "Clínica odontológica demonstrativa",
    category: "Clínica odontológica",
    city: "Capitólio",
    address: "Endereço profissional aguardando validação",
    phone: "Contato aguardando validação",
    summary: "Modelo para clínicas odontológicas com equipe, serviços, estrutura e contatos comerciais.",
    services: ["Odontologia", "Prevenção", "Reabilitação oral"],
  },
  // Base pública importada do OpenStreetMap para revisão editorial.
  {"slug": "hospital-santa-casa-pimenta", "name": "Hospital Santa Casa", "category": "Hospital", "city": "Pimenta", "address": "Endereço aguardando validação", "phone": "Contato aguardando validação", "summary": "Cadastro importado de fonte pública para validação editorial antes da publicação definitiva.", "services": ["Atendimento hospitalar", "Serviços de saúde"], "logoUrl": "/placeholders/company-logo.svg", "coverImageUrl": "/placeholders/clinic-cover.svg"},
  {"slug": "consultorio-dr-gabriel-tavares-pediatra-pimenta", "name": "Consultório Dr Gabriel Tavares Pediatra", "category": "Médico / clínica", "city": "Pimenta", "address": "Praça Tuiuti 114", "phone": "Contato aguardando validação", "summary": "Cadastro importado de fonte pública para validação editorial antes da publicação definitiva.", "services": ["Atendimento clínico", "Saúde regional"], "logoUrl": "/placeholders/company-logo.svg", "coverImageUrl": "/placeholders/clinic-cover.svg"},
  {"slug": "bruna-lopes-fisioterapia-e-pilates-pimenta", "name": "Bruna Lopes - Fisioterapia e Pilates", "category": "Fisioterapia", "city": "Pimenta", "address": "Rua Crispim Elias da Cunha 102", "phone": "Contato aguardando validação", "summary": "Cadastro importado de fonte pública para validação editorial antes da publicação definitiva.", "services": ["Fisioterapia", "Reabilitação"], "logoUrl": "/placeholders/company-logo.svg", "coverImageUrl": "/placeholders/clinic-cover.svg"},
  {"slug": "drogaria-nossa-senhora-do-carmo-arcos", "name": "Drogaria Nossa Senhora do Carmo", "category": "Farmácia", "city": "Arcos", "address": "Endereço aguardando validação", "phone": "Contato aguardando validação", "summary": "Cadastro importado de fonte pública para validação editorial antes da publicação definitiva.", "services": ["Medicamentos", "Produtos de saúde"], "logoUrl": "/placeholders/pharmacy-logo.svg", "coverImageUrl": "/placeholders/clinic-cover.svg"},
  {"slug": "hospital-municipal-arcos", "name": "Hospital Municipal", "category": "Hospital", "city": "Arcos", "address": "Endereço aguardando validação", "phone": "Contato aguardando validação", "summary": "Cadastro importado de fonte pública para validação editorial antes da publicação definitiva.", "services": ["Atendimento hospitalar", "Serviços de saúde"], "logoUrl": "/placeholders/company-logo.svg", "coverImageUrl": "/placeholders/clinic-cover.svg"},
  {"slug": "fundacao-municipal-de-saude-e-assistencia-de-arcos-fumusa-arcos", "name": "Fundação Municipal de Saúde e Assistência de Arcos - FUMUSA", "category": "Clínica", "city": "Arcos", "address": "Rua Vinte e Cinco de Dezembro 20'", "phone": "+55 37 3351 1875", "summary": "Cadastro importado de fonte pública para validação editorial antes da publicação definitiva.", "services": ["Atendimento clínico", "Saúde regional"], "logoUrl": "/placeholders/company-logo.svg", "coverImageUrl": "/placeholders/clinic-cover.svg"},
  {"slug": "hospital-municipal-sao-jose-de-arcos-arcos", "name": "Hospital Municipal Sao Jose de Arcos", "category": "Hospital", "city": "Arcos", "address": "Endereço aguardando validação", "phone": "Contato aguardando validação", "summary": "Cadastro importado de fonte pública para validação editorial antes da publicação definitiva.", "services": ["Atendimento hospitalar", "Serviços de saúde"], "logoUrl": "/placeholders/company-logo.svg", "coverImageUrl": "/placeholders/clinic-cover.svg"},
  {"slug": "santa-casa-de-arcos-arcos", "name": "Santa Casa de Arcos", "category": "Hospital", "city": "Arcos", "address": "Endereço aguardando validação", "phone": "Contato aguardando validação", "summary": "Cadastro importado de fonte pública para validação editorial antes da publicação definitiva.", "services": ["Atendimento hospitalar", "Serviços de saúde"], "logoUrl": "/placeholders/company-logo.svg", "coverImageUrl": "/placeholders/clinic-cover.svg"},
  {"slug": "unidade-basica-de-saude-zona-norte-arcos", "name": "Unidade Básica de Saúde Zona Norte", "category": "Clínica", "city": "Arcos", "address": "Rua João Jovino 335", "phone": "Contato aguardando validação", "summary": "Cadastro importado de fonte pública para validação editorial antes da publicação definitiva.", "services": ["Atendimento clínico", "Saúde regional"], "logoUrl": "/placeholders/company-logo.svg", "coverImageUrl": "/placeholders/clinic-cover.svg"},
  {"slug": "policlinica-arcos", "name": "Policlínica", "category": "Hospital", "city": "Arcos", "address": "Endereço aguardando validação", "phone": "Contato aguardando validação", "summary": "Cadastro importado de fonte pública para validação editorial antes da publicação definitiva.", "services": ["Atendimento hospitalar", "Serviços de saúde"], "logoUrl": "/placeholders/company-logo.svg", "coverImageUrl": "/placeholders/clinic-cover.svg"},
  {"slug": "farmacia-brasil-sao-roque-de-minas", "name": "Farmácia Brasil", "category": "Farmácia", "city": "São Roque de Minas", "address": "Endereço aguardando validação", "phone": "Contato aguardando validação", "summary": "Cadastro importado de fonte pública para validação editorial antes da publicação definitiva.", "services": ["Medicamentos", "Produtos de saúde"], "logoUrl": "/placeholders/pharmacy-logo.svg", "coverImageUrl": "/placeholders/clinic-cover.svg"},
  {"slug": "policlinica-municipal-sao-roque-de-minas", "name": "Policlínica Municipal", "category": "Clínica", "city": "São Roque de Minas", "address": "Endereço aguardando validação", "phone": "Contato aguardando validação", "summary": "Cadastro importado de fonte pública para validação editorial antes da publicação definitiva.", "services": ["Atendimento clínico", "Saúde regional"], "logoUrl": "/placeholders/company-logo.svg", "coverImageUrl": "/placeholders/clinic-cover.svg"},
  {"slug": "policlinica-municipal-avelino-rodrigues-da-silva-sao-roque-de-minas", "name": "Policlínica Municipal Avelino Rodrigues da Silva", "category": "Clínica", "city": "São Roque de Minas", "address": "Endereço aguardando validação", "phone": "Contato aguardando validação", "summary": "Cadastro importado de fonte pública para validação editorial antes da publicação definitiva.", "services": ["Atendimento clínico", "Saúde regional"], "logoUrl": "/placeholders/company-logo.svg", "coverImageUrl": "/placeholders/clinic-cover.svg"},
  {"slug": "hospital-municipal-sao-roque-de-minas", "name": "Hospital Municipal", "category": "Hospital", "city": "São Roque de Minas", "address": "Endereço aguardando validação", "phone": "Contato aguardando validação", "summary": "Cadastro importado de fonte pública para validação editorial antes da publicação definitiva.", "services": ["Atendimento hospitalar", "Serviços de saúde"], "logoUrl": "/placeholders/company-logo.svg", "coverImageUrl": "/placeholders/clinic-cover.svg"},
  {"slug": "hospital-municiapl-sao-roque-de-minas", "name": "Hospital Municiapl", "category": "Hospital", "city": "São Roque de Minas", "address": "Endereço aguardando validação", "phone": "Contato aguardando validação", "summary": "Cadastro importado de fonte pública para validação editorial antes da publicação definitiva.", "services": ["Atendimento hospitalar", "Serviços de saúde"], "logoUrl": "/placeholders/company-logo.svg", "coverImageUrl": "/placeholders/clinic-cover.svg"},
  {"slug": "santa-casa-de-misericordia-de-piumhi", "name": "Santa Casa de Misericórdia de Piumhi", "category": "Hospital", "city": "Piumhi", "address": "Praça Guia Lopes / região da Santa Casa", "phone": "Contato aguardando validação", "summary": "Hospital geral filantrópico de referência regional. Cadastro baseado em fonte pública e pendente de validação editorial antes da publicação comercial.", "services": ["Atendimento hospitalar", "Pronto atendimento", "Referência regional"], "logoUrl": "/placeholders/company-logo.svg", "coverImageUrl": "/placeholders/clinic-cover.svg"},
  {"slug": "consultorio-dr-gabriel-tavares-pediatra-piumhi", "name": "Consultório Dr Gabriel Tavares Pediatra", "category": "Médico / clínica", "city": "Piumhi", "address": "Praça Tuiuti 114", "phone": "Contato aguardando validação", "summary": "Cadastro importado de fonte pública para validação editorial antes da publicação definitiva.", "services": ["Atendimento clínico", "Saúde regional"], "logoUrl": "/placeholders/company-logo.svg", "coverImageUrl": "/placeholders/clinic-cover.svg"},
  {"slug": "bruna-lopes-fisioterapia-e-pilates-piumhi", "name": "Bruna Lopes - Fisioterapia e Pilates", "category": "Fisioterapia", "city": "Piumhi", "address": "Rua Crispim Elias da Cunha 102", "phone": "Contato aguardando validação", "summary": "Cadastro importado de fonte pública para validação editorial antes da publicação definitiva.", "services": ["Fisioterapia", "Reabilitação"], "logoUrl": "/placeholders/company-logo.svg", "coverImageUrl": "/placeholders/clinic-cover.svg"},
  {"slug": "samu-piumhi", "name": "SAMU Piumhi", "category": "Urgência e emergência", "city": "Piumhi", "address": "Atendimento regional / endereço operacional aguardando validação", "phone": "192", "summary": "Serviço de Atendimento Móvel de Urgência citado em fonte pública como operação iniciada em Piumhi. Cadastro institucional pendente de revisão editorial.", "services": ["Urgência", "Atendimento pré-hospitalar", "Serviço público"], "logoUrl": "/placeholders/company-logo.svg", "coverImageUrl": "/placeholders/clinic-cover.svg"},
  {"slug": "secretaria-municipal-de-saude-piumhi", "name": "Secretaria Municipal de Saúde de Piumhi", "category": "Gestão pública de saúde", "city": "Piumhi", "address": "Endereço aguardando validação", "phone": "Contato aguardando validação", "summary": "Cadastro institucional criado para organizar serviços e informações públicas de saúde do município antes da validação completa.", "services": ["Saúde pública", "Atenção básica", "Informação ao cidadão"], "logoUrl": "/placeholders/company-logo.svg", "coverImageUrl": "/placeholders/clinic-cover.svg"},
  {"slug": "unidade-basica-de-saude-piumhi", "name": "Unidade Básica de Saúde — Piumhi", "category": "Clínica / atenção básica", "city": "Piumhi", "address": "Unidade e endereço aguardando validação", "phone": "Contato aguardando validação", "summary": "Registro provisório para organizar a rede de atenção básica da cidade. Necessita confirmação de nome oficial, endereço e telefone.", "services": ["Atenção básica", "Prevenção", "Saúde da família"], "logoUrl": "/placeholders/company-logo.svg", "coverImageUrl": "/placeholders/clinic-cover.svg"},
  {"slug": "farmacia-nossa-senhora-aparecida-bambui", "name": "Farmácia Nossa Senhora Aparecida", "category": "Farmácia", "city": "Bambuí", "address": "Endereço aguardando validação", "phone": "Contato aguardando validação", "summary": "Cadastro importado de fonte pública para validação editorial antes da publicação definitiva.", "services": ["Medicamentos", "Produtos de saúde"], "logoUrl": "/placeholders/pharmacy-logo.svg", "coverImageUrl": "/placeholders/clinic-cover.svg"},
  {"slug": "farmacia-brasil-bambui", "name": "Farmácia Brasil", "category": "Farmácia", "city": "Bambuí", "address": "Rua José Augusto Chaves 404", "phone": "Contato aguardando validação", "summary": "Cadastro importado de fonte pública para validação editorial antes da publicação definitiva.", "services": ["Medicamentos", "Produtos de saúde"], "logoUrl": "/placeholders/pharmacy-logo.svg", "coverImageUrl": "/placeholders/clinic-cover.svg"},
  {"slug": "uai-farma-bambui", "name": "Uai Farma", "category": "Farmácia", "city": "Bambuí", "address": "Rua dos Expedicionários 66", "phone": "Contato aguardando validação", "summary": "Cadastro importado de fonte pública para validação editorial antes da publicação definitiva.", "services": ["Medicamentos", "Produtos de saúde"], "logoUrl": "/placeholders/pharmacy-logo.svg", "coverImageUrl": "/placeholders/clinic-cover.svg"},
  {"slug": "drogaria-souza-bambui", "name": "Drogaria Souza", "category": "Farmácia", "city": "Bambuí", "address": "Rua Alzira Torres 501", "phone": "Contato aguardando validação", "summary": "Cadastro importado de fonte pública para validação editorial antes da publicação definitiva.", "services": ["Medicamentos", "Produtos de saúde"], "logoUrl": "/placeholders/pharmacy-logo.svg", "coverImageUrl": "/placeholders/clinic-cover.svg"},
  {"slug": "lugy-cosmeticos-bambui", "name": "Lugy Cosméticos", "category": "Farmácia", "city": "Bambuí", "address": "Rua dos Expedicionários 114", "phone": "Contato aguardando validação", "summary": "Cadastro importado de fonte pública para validação editorial antes da publicação definitiva.", "services": ["Medicamentos", "Produtos de saúde"], "logoUrl": "/placeholders/pharmacy-logo.svg", "coverImageUrl": "/placeholders/clinic-cover.svg"},
  {"slug": "unidade-basica-de-saude-da-familia-dr-jurandir-chaves-bambui", "name": "Unidade Básica de Saúde da Família Dr. Jurandir Chaves", "category": "Clínica", "city": "Bambuí", "address": "Endereço aguardando validação", "phone": "Contato aguardando validação", "summary": "Cadastro importado de fonte pública para validação editorial antes da publicação definitiva.", "services": ["Atendimento clínico", "Saúde regional"], "logoUrl": "/placeholders/company-logo.svg", "coverImageUrl": "/placeholders/clinic-cover.svg"},
  {"slug": "casa-de-saude-sao-francisco-de-assis-bambui", "name": "Casa de Saúde São Francisco de Assis", "category": "Hospital", "city": "Bambuí", "address": "Endereço aguardando validação", "phone": "+55 37 34316600", "summary": "Cadastro importado de fonte pública para validação editorial antes da publicação definitiva.", "services": ["Atendimento hospitalar", "Serviços de saúde"], "logoUrl": "/placeholders/company-logo.svg", "coverImageUrl": "/placeholders/clinic-cover.svg"},
  {"slug": "farmacia-lima-bambui", "name": "Farmácia Lima", "category": "Farmácia", "city": "Bambuí", "address": "Rua Antero Torres 264", "phone": "Contato aguardando validação", "summary": "Cadastro importado de fonte pública para validação editorial antes da publicação definitiva.", "services": ["Medicamentos", "Produtos de saúde"], "logoUrl": "/placeholders/pharmacy-logo.svg", "coverImageUrl": "/placeholders/clinic-cover.svg"},
  {"slug": "naturalfarma-bambui", "name": "Naturalfarma", "category": "Farmácia", "city": "Bambuí", "address": "Endereço aguardando validação", "phone": "Contato aguardando validação", "summary": "Cadastro importado de fonte pública para validação editorial antes da publicação definitiva.", "services": ["Medicamentos", "Produtos de saúde"], "logoUrl": "/placeholders/pharmacy-logo.svg", "coverImageUrl": "/placeholders/clinic-cover.svg"},
  {"slug": "hospital-nossa-senhora-do-brasil-bambui", "name": "Hospital Nossa Senhora do Brasil", "category": "Hospital", "city": "Bambuí", "address": "Endereço aguardando validação", "phone": "Contato aguardando validação", "summary": "Cadastro importado de fonte pública para validação editorial antes da publicação definitiva.", "services": ["Atendimento hospitalar", "Serviços de saúde"], "logoUrl": "/placeholders/company-logo.svg", "coverImageUrl": "/placeholders/clinic-cover.svg"},

];

const supplementalOrganizations: Organization[] = [
  ...[
    ["Capitólio", "capitolio"],
    ["Pimenta", "pimenta"],
    ["Arcos", "arcos"],
    ["Campo Belo", "campo-belo"],
    ["São Roque de Minas", "sao-roque-de-minas"],
  ].flatMap(([city, slugCity]) => [
    {
      slug: `secretaria-municipal-de-saude-${slugCity}`,
      name: `Secretaria Municipal de Saúde de ${city}`,
      category: "Gestão pública de saúde",
      city,
      address: "Endereço aguardando validação",
      phone: "Contato aguardando validação",
      summary: "Cadastro institucional criado para organizar serviços e informações públicas de saúde do município antes da validação completa.",
      services: ["Saúde pública", "Atenção básica", "Informação ao cidadão"],
      logoUrl: "/placeholders/company-logo.svg",
      coverImageUrl: "/placeholders/clinic-cover.svg",
    },
    {
      slug: `unidade-basica-de-saude-${slugCity}`,
      name: `Unidade Básica de Saúde — ${city}`,
      category: "Clínica / atenção básica",
      city,
      address: "Unidade e endereço aguardando validação",
      phone: "Contato aguardando validação",
      summary: "Registro provisório para organizar a rede de atenção básica da cidade. Necessita confirmação de nome oficial, endereço e telefone.",
      services: ["Atenção básica", "Prevenção", "Saúde da família"],
      logoUrl: "/placeholders/company-logo.svg",
      coverImageUrl: "/placeholders/clinic-cover.svg",
    },
    {
      slug: `clinica-multiprofissional-demonstrativa-${slugCity}`,
      name: `Clínica multiprofissional demonstrativa — ${city}`,
      category: "Clínica multiprofissional",
      city,
      address: "Endereço profissional aguardando validação",
      phone: "Contato aguardando validação",
      summary: "Modelo comercial para clínicas, consultórios integrados e centros de especialidades da cidade.",
      services: ["Consultas", "Atendimento multiprofissional", "Prevenção"],
      logoUrl: "/placeholders/company-logo.svg",
      coverImageUrl: "/placeholders/clinic-cover.svg",
    },
    {
      slug: `laboratorio-demonstrativo-${slugCity}`,
      name: `Laboratório demonstrativo — ${city}`,
      category: "Laboratório",
      city,
      address: "Endereço comercial aguardando validação",
      phone: "Contato aguardando validação",
      summary: "Modelo comercial para laboratórios, coleta, exames e serviços de apoio diagnóstico.",
      services: ["Exames laboratoriais", "Coleta", "Apoio diagnóstico"],
      logoUrl: "/placeholders/company-logo.svg",
      coverImageUrl: "/placeholders/clinic-cover.svg",
    },
    {
      slug: `farmacia-demonstrativa-${slugCity}`,
      name: `Farmácia demonstrativa — ${city}`,
      category: "Farmácia",
      city,
      address: "Endereço comercial aguardando validação",
      phone: "Contato aguardando validação",
      summary: "Modelo comercial para farmácias, drogarias e serviços de orientação em saúde.",
      services: ["Medicamentos", "Produtos de saúde", "Atenção farmacêutica"],
      logoUrl: "/placeholders/pharmacy-logo.svg",
      coverImageUrl: "/placeholders/clinic-cover.svg",
    },
  ]),
];

export const organizations: Organization[] = [...baseOrganizations, ...supplementalOrganizations];

export const cities = ["Piumhi", "Capitólio", "Pimenta", "Arcos", "Campo Belo", "Bambuí", "São Roque de Minas"];
export const professions = ["Médico", "Dentista", "Psicólogo", "Fisioterapeuta", "Nutricionista", "Fonoaudiólogo", "Enfermeiro", "Farmacêutico", "Educador físico"];

export const articles = [
  { slug: "prevencao-na-rotina", category: "Prevenção", title: "Como transformar prevenção em parte da rotina", excerpt: "Informação regional, fontes claras e orientação para buscar atendimento profissional.", city: "Regional" },
  { slug: "saude-e-longevidade", category: "Longevidade", title: "Saúde e longevidade: cuidados em cada fase", excerpt: "Uma pauta editorial conectada a especialistas e serviços da região.", city: "Regional" },
  { slug: "conexao-saude", category: "Podcast", title: "Conexão Saúde: conhecimento que aproxima", excerpt: "Episódios, convidados, transcrições e conteúdos complementares.", city: "Regional" },
];

export const podcasts = [
  { slug: "radiologia-odontologica", guest: "Rodrigo Soares Costa", role: "Tecnólogo em radiologia", topic: "Radiologia odontológica: como a tecnologia transforma os tratamentos", date: "14 de julho", duration: "Ao vivo às 19h", status: "Próximo episódio" },
  { slug: "implantodontia-reabilitacao", guest: "Lívia Pereira", role: "Dentista", topic: "Do cuidado à transformação: implantodontia, reabilitação oral e prevenção", date: "30 de junho", duration: "Episódio completo", status: "Disponível" },
  { slug: "blefaroplastia", guest: "Mírian L. Sansoni", role: "Oftalmologista", topic: "Blefaroplastia: saúde, estética e qualidade de vida", date: "9 de junho", duration: "Episódio completo", status: "Disponível" },
];

export const magazineEditions = [
  { number: "14ª", year: "2026", title: "Saúde, bem-estar e qualidade de vida", description: "A nova fase editorial da Guia Saúde: informação que conecta profissionais, marcas e a comunidade regional.", featured: true },
  { number: "13ª", year: "2025", title: "Cuidado que transforma", description: "Entrevistas, histórias e orientações para escolhas mais conscientes em saúde.", featured: false },
  { number: "12ª", year: "2025", title: "Conexões para viver melhor", description: "Uma edição dedicada aos especialistas e iniciativas que movimentam a região.", featured: false },
];

export const cityDetails: Record<string, { name: string; intro: string; region: string }> = {
  piumhi: { name: "Piumhi", intro: "Profissionais, clínicas, serviços e informação em saúde para quem vive em Piumhi e região.", region: "Centro-Oeste de Minas" },
  capitolio: { name: "Capitólio", intro: "Um guia local para encontrar cuidado e acompanhar os assuntos de saúde de Capitólio.", region: "Região da Serra da Canastra" },
  pimenta: { name: "Pimenta", intro: "Serviços, especialistas e conteúdo de saúde reunidos em uma página dedicada a Pimenta.", region: "Centro-Oeste de Minas" },
  arcos: { name: "Arcos", intro: "Encontre profissionais e empresas da saúde e acompanhe conteúdos relevantes para Arcos.", region: "Centro-Oeste de Minas" },
  "campo-belo": { name: "Campo Belo", intro: "O ecossistema de saúde de Campo Belo organizado para facilitar escolhas e conexões.", region: "Oeste de Minas" },
  bambui: { name: "Bambuí", intro: "Informação, prevenção e serviços de saúde próximos da comunidade de Bambuí.", region: "Região da Serra da Canastra" },
  "sao-roque-de-minas": { name: "São Roque de Minas", intro: "Um ponto de encontro para profissionais, serviços e informação em saúde na Serra da Canastra.", region: "Serra da Canastra" },
};
