-- Seed das 7 cidades da carteira Guia Saúde.
-- Idempotente: reexecutar atualiza os dados sem duplicar (conflito por slug).
-- Aplicar depois da migration 0007_cities_enrichment.
--   Ex.: wrangler d1 execute <DB> --file=scripts/seed-cities.sql --remote
-- Fonte da verdade em código: lib/cities.ts. População = estimativa IBGE 2022 (validar).

INSERT INTO cities (ibge_code, name, slug, state, gentilic, microregion, health_region, region, population, intro, seo_description, highlights, active) VALUES
('3151206','Piumhi','piumhi','MG','piumhiense','Microrregião de Piumhi','Região de Saúde de Piumhi','Centro-Oeste de Minas',35000,'Profissionais, clínicas, serviços e informação em saúde para quem vive em Piumhi e região.','Guia de saúde de Piumhi (MG): encontre médicos, dentistas, clínicas, laboratórios e farmácias, com conteúdo, podcast e revista regional.','["Cidade-polo da região de saúde","Hospital de referência (Santa Casa)","Base de profissionais em formação prioritária"]',1),
('3112505','Capitólio','capitolio','MG','capitolino','Microrregião de Piumhi','Região de Saúde de Piumhi','Serra da Canastra · Lago de Furnas',9100,'Um guia local para encontrar cuidado e acompanhar os assuntos de saúde de Capitólio.','Guia de saúde de Capitólio (MG): profissionais, clínicas e serviços de saúde na região do Lago de Furnas e da Serra da Canastra.','["Alta sazonalidade turística (Furnas)","Demanda por saúde e estética de temporada","Praça de valor para marcas de bem-estar"]',1),
('3150539','Pimenta','pimenta','MG','pimentense','Microrregião de Piumhi','Região de Saúde de Piumhi','Lago de Furnas · Centro-Oeste de Minas',8900,'Serviços, especialistas e conteúdo de saúde reunidos em uma página dedicada a Pimenta.','Guia de saúde de Pimenta (MG): médicos, fisioterapeutas, farmácias e serviços de saúde da cidade e do entorno do Lago de Furnas.','["Vizinha direta de Piumhi e Capitólio","Rede de atenção básica ativa","Boa entrada para pacotes regionais"]',1),
('3104502','Arcos','arcos','MG','arcoense','Microrregião de Formiga','Região de Saúde de Formiga','Centro-Oeste de Minas',40000,'Encontre profissionais e empresas da saúde e acompanhe conteúdos relevantes para Arcos.','Guia de saúde de Arcos (MG): hospitais, clínicas, laboratórios, farmácias e especialistas com conteúdo e presença regional.','["Segundo maior mercado da carteira","Parque hospitalar e laboratorial relevante","Economia industrial com público consumidor"]',1),
('3126109','Formiga','formiga','MG','formiguense','Microrregião de Formiga','Região de Saúde de Formiga','Centro-Oeste de Minas',35000,'Profissionais, clínicas e serviços de saúde reunidos para quem vive em Formiga e no entorno.','Guia de saúde de Formiga (MG): médicos, clínicas, especialidades, laboratórios e farmácias, com conteúdo e presença regional.','["Sede da região de saúde (referência de Arcos e entorno)","Polo universitário e industrial","Mercado forte para especialidades e clínicas"]',1),
('3111309','Campo Belo','campo-belo','MG','campo-belense','Microrregião de Campo Belo','Região de Saúde de Campo Belo','Oeste de Minas',54000,'O ecossistema de saúde de Campo Belo organizado para facilitar escolhas e conexões.','Guia de saúde de Campo Belo (MG): médicos, clínicas, especialidades, laboratórios e serviços de saúde com conteúdo regional.','["Maior mercado da carteira","Cidade-polo de saúde do Oeste mineiro","Densidade de especialidades e clínicas"]',1),
('3105002','Bambuí','bambui','MG','bambuiense','Microrregião de Piumhi','Região de Saúde de Piumhi','Serra da Canastra · Centro-Oeste de Minas',23000,'Informação, prevenção e serviços de saúde próximos da comunidade de Bambuí.','Guia de saúde de Bambuí (MG): profissionais, farmácias, hospitais e clínicas da cidade, com conteúdo e serviços de saúde.','["Presença de instituto federal (público jovem)","Rede de farmácias e hospitais mapeada","Cidade média com fluxo regional"]',1),
('3161908','São Roque de Minas','sao-roque-de-minas','MG','são-roquense','Microrregião de Piumhi','Região de Saúde de Piumhi','Serra da Canastra',7200,'Um ponto de encontro para profissionais, serviços e informação em saúde na Serra da Canastra.','Guia de saúde de São Roque de Minas (MG): serviços, profissionais e informação de saúde na porta da Serra da Canastra.','["Porta de entrada da Serra da Canastra","Forte apelo de turismo e natureza","Praça premium para marcas regionais"]',1)
ON CONFLICT(slug) DO UPDATE SET
  ibge_code=excluded.ibge_code, name=excluded.name, state=excluded.state, gentilic=excluded.gentilic,
  microregion=excluded.microregion, health_region=excluded.health_region, region=excluded.region,
  population=excluded.population, intro=excluded.intro, seo_description=excluded.seo_description,
  highlights=excluded.highlights, active=excluded.active;
