"use client";

import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { Suspense, useEffect, useState } from "react";
import { ArrowLeft, ArrowUpRight, Building2, ChevronRight, MapPin, Phone, Search, SlidersHorizontal, Sparkles, Stethoscope, X } from "lucide-react";
import { FavoriteButton } from "@/components/FavoriteButton";
import { ProfessionalImage } from "@/components/ProfessionalImage";
import { ProfessionIcon } from "@/components/ProfessionIcon";
import { organizations, professions } from "@/lib/data";
import { publicProfessionals } from "@/lib/public-professionals";
import { filterOrganizations, filterProfessionals } from "@/lib/search";
import { categoryOptionsFor } from "@/lib/service-taxonomy";

const PAGE_SIZE = 18;
const quickSpecialties = ["Cardiologia", "Dermatologia", "Ginecologia", "Ortopedia", "Pediatria", "Psicologia"];
function param(value: string | null) { return value ?? ""; }
function publicAddress(address?: string) { return address && !/endere[cç]o\s+(aguardando validação|a validar|a confirmar)/i.test(address) ? address : ""; }
function professionLabel(item: { profession: string; name: string }) { if (/^Dra\.?\s/i.test(item.name)) return item.profession === "Médico" ? "Médica" : item.profession; if (/^Dr\.?\s/i.test(item.name)) return item.profession; return ({ "Médico": "Medicina", "Psicólogo": "Psicologia", "Fonoaudiólogo": "Fonoaudiologia", "Enfermeiro": "Enfermagem", "Educador físico": "Educação Física" } as Record<string,string>)[item.profession] ?? item.profession; }
function directContact(whatsapp?: string, phone?: string) { const w=(whatsapp??"").replace(/\D/g,""); if(w.length>=10)return{href:`https://wa.me/${w.startsWith("55")?w:`55${w}`}`,label:"WhatsApp"}; const p=(phone??"").replace(/\D/g,""); if(p.length>=10)return{href:`tel:+55${p}`,label:"Ligar"}; return null; }

function SearchDirectory(){
 const params=useSearchParams(),q=param(params.get("q")),profession=param(params.get("profissao")),specialty=param(params.get("especialidade")),category=param(params.get("categoria")),typeParam=param(params.get("tipo"));
 const type=({profissionais:"profissionais",professionals:"profissionais",empresas:"servicos",services:"servicos"}[typeParam]??"todos") as "todos"|"profissionais"|"servicos"; const city="Piumhi"; const [visibleCount,setVisibleCount]=useState(PAGE_SIZE);
 const filters={query:q,city,profession,specialty,category,type}; const professionalSource=publicProfessionals; const organizationSource=organizations.filter(i=>i.city===city); const hasProfessionalFocus=Boolean(profession||specialty); const professionalResults=type==="servicos"?[]:filterProfessionals(professionalSource,filters); const organizationResults=type==="profissionais"||(type==="todos"&&hasProfessionalFocus)?[]:filterOrganizations(organizationSource,filters); const total=professionalResults.length+organizationResults.length; const isLanding=!q&&!profession&&!specialty&&!category&&type==="todos"; const categoryChoices=categoryOptionsFor(organizationSource).sort((a,b)=>b.count-a.count); const specialtyChoices=Array.from(new Set(filterProfessionals(professionalSource,{city}).map(i=>i.specialty).filter(Boolean))).sort((a,b)=>a.localeCompare(b,"pt-BR")); const visibleProfessionals=professionalResults.slice(0,visibleCount),visibleOrganizations=organizationResults.slice(0,visibleCount);
 useEffect(()=>{const timer=window.setTimeout(()=>setVisibleCount(PAGE_SIZE),0);return()=>window.clearTimeout(timer)},[q,profession,specialty,category,type]);
 function hrefFor(nextType:typeof type){const s=new URLSearchParams();if(q)s.set("q",q);s.set("cidade","piumhi");if(nextType!=="servicos"&&profession)s.set("profissao",profession);if(nextType!=="servicos"&&specialty)s.set("especialidade",specialty);if(nextType!=="profissionais"&&category)s.set("categoria",category);if(nextType!=="todos")s.set("tipo",nextType==="servicos"?"services":"professionals");return`/buscar?${s.toString()}`}
 function clearFilter(key:string){const s=new URLSearchParams(params.toString());s.delete(key);s.set("cidade","piumhi");return`/buscar?${s.toString()}`}
 return <main className={`native-search-screen${isLanding?" native-search-landing":" native-search-results"}`}><div className="native-search-aura" aria-hidden="true"/><div className="native-search-shell">
  <header className="native-search-header"><Link className="native-search-back" href="/" aria-label="Voltar"><ArrowLeft size={20}/></Link><div className="native-search-title"><h1>Buscar</h1><p>Encontre profissionais, clínicas, exames e muito mais.</p></div></header>
  <form className="native-search-form" action="/buscar" role="search"><Search size={19}/><input name="q" defaultValue={q} autoComplete="off" enterKeyHint="search" aria-label="O que você está buscando?" placeholder="O que você está buscando?"/><input type="hidden" name="cidade" value="piumhi"/>{type!=="todos"?<input type="hidden" name="tipo" value={type==="servicos"?"services":"professionals"}/>:null}<button type="submit" aria-label="Buscar"><Search size={19}/></button></form>
  <nav className="native-search-tabs" aria-label="Modalidade de busca"><Link href={hrefFor("todos")} className={type==="todos"?"active":""}>Todos</Link><Link href={hrefFor("profissionais")} className={type==="profissionais"?"active":""}>Profissionais</Link><Link href={hrefFor("servicos")} className={type==="servicos"?"active":""}>Clínicas</Link></nav>
  {isLanding?<section className="native-search-discovery"><div className="native-section-head"><h2>Especialidades</h2><Link href="/buscar/especialidades">Ver todas <ChevronRight size={15}/></Link></div><div className="native-specialty-grid">{quickSpecialties.map((label,index)=><Link key={label} className={`native-specialty-card tone-${index+1}`} href={`/buscar?q=${encodeURIComponent(label)}&cidade=piumhi&tipo=professionals`}><span><Stethoscope size={25} strokeWidth={1.55}/></span><strong>{label}</strong></Link>)}</div><div className="native-search-shortcuts"><Link href="/buscar?cidade=piumhi&tipo=professionals"><span><Stethoscope size={20}/></span><div><strong>Todos os profissionais</strong><small>{professionalSource.length} perfis no guia</small></div><ChevronRight size={17}/></Link><Link href="/buscar?cidade=piumhi&tipo=services"><span><Building2 size={20}/></span><div><strong>Clínicas e serviços</strong><small>Atendimento em Piumhi</small></div><ChevronRight size={17}/></Link></div></section>:<>
   <section className="native-results-toolbar"><div><span>{type==="profissionais"?professionalResults.length:type==="servicos"?organizationResults.length:total}</span><p>{type==="profissionais"?"profissionais encontrados":type==="servicos"?"serviços encontrados":"resultados encontrados"}</p></div><details className="native-filter-sheet"><summary><SlidersHorizontal size={16}/> Filtros</summary><div className="native-filter-backdrop"/><div className="native-filter-panel"><div className="native-filter-heading"><div><small>Refine sua busca</small><h2>Filtros</h2></div><span><X size={18}/></span></div><form action="/buscar"><input type="hidden" name="cidade" value="piumhi"/>{type!=="todos"?<input type="hidden" name="tipo" value={type==="servicos"?"services":"professionals"}/>:null}<label>Buscar<input name="q" defaultValue={q} placeholder="Nome ou especialidade"/></label>{type!=="servicos"?<><label>Profissão<select name="profissao" defaultValue={profession}><option value="">Todas</option>{professions.map(i=><option key={i}>{i}</option>)}</select></label><label>Especialidade<select name="especialidade" defaultValue={specialty}><option value="">Todas</option>{specialtyChoices.map(i=><option key={i}>{i}</option>)}</select></label></>:null}{type!=="profissionais"?<label>Tipo de serviço<select name="categoria" defaultValue={category}><option value="">Todos</option>{categoryChoices.map(i=><option key={i.key} value={i.key}>{i.label}</option>)}</select></label>:null}<button type="submit">Aplicar filtros</button></form></div></details></section>
   {(q||profession||specialty||category)?<div className="native-active-filters">{q?<Link href={clearFilter("q")}>{q}<X size={11}/></Link>:null}{profession?<Link href={clearFilter("profissao")}>{profession}<X size={11}/></Link>:null}{specialty?<Link href={clearFilter("especialidade")}>{specialty}<X size={11}/></Link>:null}{category?<Link href={clearFilter("categoria")}>{category}<X size={11}/></Link>:null}</div>:null}
   {type==="servicos"&&!q&&!category?<section className="native-category-picker"><div className="native-section-head"><h2>O que você procura?</h2><span>Escolha uma categoria</span></div><div className="native-category-grid">{categoryChoices.map(i=><Link key={i.key} href={`/buscar?categoria=${encodeURIComponent(i.key)}&cidade=piumhi&tipo=services`}><span><Building2 size={19}/></span><strong>{i.label}</strong><small>{i.count}</small></Link>)}</div></section>:null}
   {total===0?<section className="native-empty-state"><span><Search size={24}/></span><h2>Nada encontrado</h2><p>Tente outro termo ou remova alguns filtros.</p><Link href="/buscar?cidade=piumhi">Limpar busca</Link></section>:null}
   {professionalResults.length>0?<section className="native-result-section">{type==="todos"?<div className="native-section-head"><h2>Profissionais</h2></div>:null}<div className="native-professional-list">{visibleProfessionals.map((item,index)=>{const contact=item.featured?directContact(item.whatsapp,item.phone):null;return <article className={`native-professional-card${item.featured?" featured":""}`} key={item.slug}>{item.featured?<span className="native-featured"><Sparkles size={11}/> Destaque</span>:null}<div className={`native-professional-avatar${item.imageUrl?" has-photo":""}`}>{item.imageUrl?<ProfessionalImage src={item.imageUrl} sizes="72px" eager={index<2}/>:<ProfessionIcon profession={item.profession}/>}</div><div className="native-professional-copy"><div className="native-card-name"><div><small>{professionLabel(item)}</small><h2>{item.name}</h2></div><FavoriteButton professional={{slug:item.slug,name:item.name,profession:item.profession,specialty:item.specialty,city:item.city,organization:item.organization,imageUrl:item.imageUrl}} compact/></div><div className="native-card-tags"><span><MapPin size={11}/> {item.city}</span>{item.specialty?<span>{item.specialty}</span>:null}</div>{item.organization?<p>{item.organization}</p>:null}</div><div className="native-card-actions">{contact?<a className="primary" href={contact.href} target={contact.href.startsWith("http")?"_blank":undefined} rel={contact.href.startsWith("http")?"noreferrer":undefined}><Phone size={14}/> {contact.label}</a>:null}<Link className={contact?"":"primary"} href={`/profissionais/${item.slug}`}>Ver perfil <ArrowUpRight size={14}/></Link></div></article>})}</div>{professionalResults.length>visibleProfessionals.length?<button className="native-load-more" type="button" onClick={()=>setVisibleCount(c=>c+PAGE_SIZE)}>Carregar mais profissionais</button>:null}</section>:null}
   {organizationResults.length>0&&!(type==="servicos"&&!q&&!category)?<section className="native-result-section">{type==="todos"?<div className="native-section-head"><h2>Clínicas e serviços</h2></div>:null}<div className="native-business-list">{visibleOrganizations.map(item=>{const contact=directContact(undefined,item.phone);return <article className="native-business-card" key={item.slug}><div className="native-business-logo" style={{backgroundImage:`url(${item.logoUrl||"/placeholders/company-logo.svg"})`}}/><div className="native-business-copy"><small>{item.category}</small><h2>{item.name}</h2><div className="native-card-tags"><span><MapPin size={11}/> {item.city}</span></div>{publicAddress(item.address)?<p>{publicAddress(item.address)}</p>:null}{item.services.length?<p>{item.services.slice(0,2).join(" · ")}</p>:null}</div><div className="native-card-actions">{contact?<a className="primary" href={contact.href}><Phone size={14}/> {contact.label}</a>:null}<Link className={contact?"":"primary"} href={`/empresas/${item.slug}`}>Ver detalhes <ArrowUpRight size={14}/></Link></div></article>})}</div>{organizationResults.length>visibleOrganizations.length?<button className="native-load-more" type="button" onClick={()=>setVisibleCount(c=>c+PAGE_SIZE)}>Carregar mais serviços</button>:null}</section>:null}
  </>}
 </div></main>
}
export default function SearchPage(){return <Suspense fallback={<main className="native-search-screen"><div className="native-search-loading">Carregando busca…</div></main>}><SearchDirectory/></Suspense>}
