"use client";

import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { Suspense, useEffect, useMemo, useState, type ComponentType, type FormEvent } from "react";
import { Activity, ArrowLeft, ArrowUpRight, Baby, Bone, Brain, Building2, ChevronDown, ChevronRight, Ellipsis, Eye, HeartPulse, MapPin, MessageCircle, Navigation, Phone, Search, SlidersHorizontal, Sparkles, Stethoscope, Venus, X } from "lucide-react";
import { FavoriteButton } from "@/components/FavoriteButton";
import { ProfessionalImage } from "@/components/ProfessionalImage";
import { ProfessionIcon } from "@/components/ProfessionIcon";
import { organizations, professions } from "@/lib/data";
import { isFeaturedProfessional } from "@/lib/featured-professionals";
import { publicProfessionals } from "@/lib/public-professionals";
import { filterOrganizations, filterProfessionals } from "@/lib/search";
import { categoryOptionsFor } from "@/lib/service-taxonomy";

const PAGE_SIZE = 18;
type SpecialtyIcon = ComponentType<{ size?: number; strokeWidth?: number }>;
const quickSpecialties: Array<{label:string; query:string; Icon:SpecialtyIcon}> = [
 {label:"Cardiologia",query:"Cardiologia",Icon:HeartPulse},{label:"Dermatologia",query:"Dermatologia",Icon:Sparkles},{label:"Ginecologia",query:"Ginecologia",Icon:Venus},{label:"Ortopedia",query:"Ortopedia",Icon:Bone},{label:"Pediatria",query:"Pediatria",Icon:Baby},{label:"Psicologia",query:"Psicologia",Icon:Brain},{label:"Odontologia",query:"Dentista",Icon:Activity},{label:"Oftalmologia",query:"Oftalmologia",Icon:Eye},{label:"Psiquiatria",query:"Psiquiatria",Icon:Brain},{label:"Pneumologia",query:"Pneumologia",Icon:Activity},{label:"Clínica médica",query:"Clínica Médica",Icon:Stethoscope},{label:"Outras especialidades",query:"",Icon:Ellipsis},
];
function param(value:string|null){return value??""}
function publicAddress(address?:string){return address&&!/endere[cç]o\s+(aguardando validação|a validar|a confirmar)/i.test(address)?address:""}
function professionLabel(item:{profession:string;name:string}){if(/^Dra\.?\s/i.test(item.name))return item.profession==="Médico"?"Médica":item.profession;if(/^Dr\.?\s/i.test(item.name))return item.profession;return({"Médico":"Medicina","Psicólogo":"Psicologia","Fonoaudiólogo":"Fonoaudiologia","Enfermeiro":"Enfermagem","Educador físico":"Educação Física"}as Record<string,string>)[item.profession]??item.profession}
function directContact(whatsapp?:string,phone?:string){const w=(whatsapp??"").replace(/\D/g,"");if(w.length>=10)return{href:`https://wa.me/${w.startsWith("55")?w:`55${w}`}`,label:"WhatsApp"};const p=(phone??"").replace(/\D/g,"");if(p.length>=10)return{href:`tel:+55${p}`,label:"Ligar"};return null}
function neighborhoodOf(org?:string){if(!org)return"";const tail=org.split(",").map(p=>p.trim()).filter(Boolean).at(-1)??"";return tail&&tail.length<=22&&!/\d/.test(tail)?tail:""}
function publicSummaryOf(summary?:string){return summary&&!/(a validar|aguardando validação|pendente|em revisão|a confirmar)/i.test(summary)?summary:""}
function registrationSigla(reg?:string){if(!reg)return"";const s=reg.split("·")[0].replace(/\d+/g,"").trim();return /[A-Za-z]{2}/.test(s)?s:""}

function SearchDirectory(){
 const router=useRouter();
 const params=useSearchParams(),q=param(params.get("q")),profession=param(params.get("profissao")),specialty=param(params.get("especialidade")),category=param(params.get("categoria")),typeParam=param(params.get("tipo"));
 const type=({profissionais:"profissionais",professionals:"profissionais",empresas:"servicos",services:"servicos"}[typeParam]??"todos")as"todos"|"profissionais"|"servicos";const city="Piumhi";const[visibleCount,setVisibleCount]=useState(PAGE_SIZE);const[refineOpen,setRefineOpen]=useState(false);const[refineProfession,setRefineProfession]=useState(profession);const[refineSpecialty,setRefineSpecialty]=useState(specialty);const[refineName,setRefineName]=useState("");const pharmacyActive=type==="servicos"&&category==="farmacias";const examsActive=type==="servicos"&&q.toLocaleLowerCase("pt-BR")==="exames";const clinicsActive=type==="servicos"&&!pharmacyActive&&!examsActive;
 const filters={query:q,city,profession,specialty,category,type};const professionalSource=publicProfessionals;const organizationSource=organizations.filter(i=>i.city===city);const hasProfessionalFocus=Boolean(profession||specialty);const professionalResults=type==="servicos"?[]:filterProfessionals(professionalSource,filters);const organizationResults=type==="profissionais"||(type==="todos"&&hasProfessionalFocus)?[]:filterOrganizations(organizationSource,filters);const total=professionalResults.length+organizationResults.length;const isLanding=!q&&!profession&&!specialty&&!category&&type==="todos";const categoryChoices=categoryOptionsFor(organizationSource).sort((a,b)=>b.count-a.count);const specialtyChoices=Array.from(new Set(filterProfessionals(professionalSource,{city}).map(i=>i.specialty).filter(Boolean))).sort((a,b)=>a.localeCompare(b,"pt-BR"));const visibleProfessionals=professionalResults.slice(0,visibleCount),visibleOrganizations=organizationResults.slice(0,visibleCount);
 const refineSpecialties=useMemo(()=>Array.from(new Set(filterProfessionals(professionalSource,{city,profession:refineProfession}).map(i=>i.specialty).filter(Boolean))).sort((a,b)=>a.localeCompare(b,"pt-BR")),[professionalSource,refineProfession]);
 const effectiveRefineSpecialty=refineSpecialty&&refineSpecialties.includes(refineSpecialty)?refineSpecialty:"";
 useEffect(()=>{const timer=window.setTimeout(()=>setVisibleCount(PAGE_SIZE),0);return()=>window.clearTimeout(timer)},[q,profession,specialty,category,type]);
 function clearFilter(key:string){const s=new URLSearchParams(params.toString());s.delete(key);s.set("cidade","piumhi");return`/buscar?${s.toString()}`}
 function submitRefine(event:FormEvent<HTMLFormElement>){event.preventDefault();const s=new URLSearchParams();s.set("cidade","piumhi");s.set("tipo","professionals");const name=refineName.trim();if(name)s.set("q",name);if(refineProfession)s.set("profissao",refineProfession);if(effectiveRefineSpecialty)s.set("especialidade",effectiveRefineSpecialty);setRefineOpen(false);router.push(`/buscar?${s.toString()}`)}
 const[orderBy,setOrderBy]=useState("relevancia");
 const bairro=param(params.get("bairro")),onlyContact=params.get("contato")==="1",onlyFeatured=params.get("destaque")==="1";
 const bairroChoices=Array.from(new Set(filterProfessionals(professionalSource,{city}).map(i=>neighborhoodOf(i.organization)).filter(Boolean))).sort((a,b)=>a.localeCompare(b,"pt-BR"));
 const gssProfBase=professionalResults.filter(p=>(!bairro||neighborhoodOf(p.organization)===bairro)&&(!onlyContact||directContact(p.whatsapp,p.phone)!==null)&&(!onlyFeatured||isFeaturedProfessional(p.slug)));
 const gssProf=orderBy==="nome"?[...gssProfBase].sort((a,b)=>a.name.localeCompare(b.name,"pt-BR")):gssProfBase;
 const gssVisibleProf=gssProf.slice(0,visibleCount);
 const crumbLabel=type==="profissionais"?"Profissionais em Piumhi":type==="servicos"?"Clínicas e serviços em Piumhi":"Busca em Piumhi";
 const gssCount=type==="servicos"?organizationResults.length:gssProf.length+organizationResults.length;
 const gssCountLabel=type==="servicos"?(gssCount===1?"serviço":"serviços"):(gssCount===1?"profissional":"profissionais");
 const gssContext=(specialty||q)?`${specialty||q} em Piumhi`:"em Piumhi";
 const desktop=<div className="gss"><div className="gss-inner">
   <nav className="gss-crumb"><Link href="/">Início</Link><span aria-hidden="true">/</span><span>{crumbLabel}</span></nav>
   <form className="gss-search" action="/buscar" role="search"><input type="hidden" name="cidade" value="piumhi"/>{typeParam?<input type="hidden" name="tipo" value={typeParam}/>:null}<span className="gss-search-field"><Search size={20}/><input name="q" defaultValue={q} placeholder="O que você procura?" aria-label="Buscar" autoComplete="off" enterKeyHint="search"/></span><span className="gss-search-div" aria-hidden="true"/><span className="gss-search-city"><MapPin size={17}/> Piumhi <ChevronDown size={15}/></span><button type="submit">Buscar</button></form>
   <nav className="gss-tabs" aria-label="Modalidade de busca"><Link href="/buscar?cidade=piumhi&tipo=professionals" className={type==="profissionais"?"active":""}>Profissionais</Link><Link href="/buscar?cidade=piumhi&tipo=services" className={clinicsActive?"active":""}>Clínicas</Link><Link href="/buscar?categoria=farmacias&cidade=piumhi&tipo=services" className={pharmacyActive?"active":""}>Farmácias</Link><Link href="/buscar?q=exames&cidade=piumhi&tipo=services" className={examsActive?"active":""}>Exames</Link></nav>
   <div className="gss-layout">
     <aside className="gss-aside" aria-label="Refinar busca"><form action="/buscar"><input type="hidden" name="cidade" value="piumhi"/>{typeParam?<input type="hidden" name="tipo" value={typeParam}/>:null}{q?<input type="hidden" name="q" value={q}/>:null}<h2>Refinar</h2>{type!=="servicos"?<><label>Profissão<select name="profissao" defaultValue={profession}><option value="">Todas</option>{professions.map(i=><option key={i}>{i}</option>)}</select></label><label>Especialidade<select name="especialidade" defaultValue={specialty}><option value="">Todas</option>{specialtyChoices.map(i=><option key={i}>{i}</option>)}</select></label><label>Bairro<select name="bairro" defaultValue={bairro}><option value="">Todos</option>{bairroChoices.map(i=><option key={i}>{i}</option>)}</select></label></>:null}{type!=="profissionais"?<label>Tipo de serviço<select name="categoria" defaultValue={category}><option value="">Todos</option>{categoryChoices.map(i=><option key={i.key} value={i.key}>{i.label}</option>)}</select></label>:null}{type!=="servicos"?<div className="gss-checks"><label className="gss-check"><input type="checkbox" name="contato" value="1" defaultChecked={onlyContact}/><span>Com contato direto</span></label><label className="gss-check"><input type="checkbox" name="destaque" value="1" defaultChecked={onlyFeatured}/><span>Perfis em destaque</span></label></div>:null}<button type="submit">Aplicar filtros</button>{(q||profession||specialty||category||bairro||onlyContact||onlyFeatured)?<Link className="gss-aside-clear" href="/buscar?cidade=piumhi">Limpar</Link>:null}</form></aside>
     <div className="gss-results">
       <div className="gss-results-head"><p><strong>{gssCount}</strong> {gssCountLabel} <span>· {gssContext}</span></p>{type!=="servicos"?<label className="gss-sort">Ordenar: <select value={orderBy} onChange={e=>setOrderBy(e.target.value)}><option value="relevancia">Relevância</option><option value="nome">Nome (A–Z)</option></select><ChevronDown size={14}/></label>:null}</div>
       {gssCount===0?<div className="gss-empty"><span><Search size={22}/></span><h3>Nada encontrado</h3><p>Tente outro termo ou remova alguns filtros.</p><Link href="/buscar?cidade=piumhi">Limpar busca</Link></div>:null}
       {gssProf.length>0?<div className="gss-list">{gssVisibleProf.map((item,index)=>{const contact=directContact(item.whatsapp,item.phone);const bairroTag=neighborhoodOf(item.organization);const sigla=registrationSigla(item.registration);const resumo=publicSummaryOf(item.summary);const featured=isFeaturedProfessional(item.slug);return <article className={`gss-card${featured?" is-featured":""}`} key={item.slug}><div className="gss-card-photo">{item.imageUrl?<ProfessionalImage src={item.imageUrl} sizes="132px" eager={index<2}/>:<ProfessionIcon profession={item.profession}/>}</div><div className="gss-card-body"><div className="gss-card-kicker"><span>{item.specialty||professionLabel(item)}</span>{featured?<em>DESTAQUE</em>:null}</div><h3>{item.name}</h3>{resumo?<p>{resumo}</p>:null}<div className="gss-card-pills">{sigla?<span>{sigla}</span>:null}{bairroTag?<span><MapPin size={13}/> {bairroTag}</span>:null}{item.organization?<span><Building2 size={13}/> Clínica parceira</span>:null}</div></div><div className="gss-card-actions">{contact?<a className="gss-a-primary" href={contact.href} target={contact.label==="WhatsApp"?"_blank":undefined} rel={contact.label==="WhatsApp"?"noreferrer":undefined}>{contact.label==="WhatsApp"?<MessageCircle size={18}/>:<Phone size={18}/>} {contact.label}</a>:null}<Link className="gss-a-see" href={`/profissionais/${item.slug}`}>Ver perfil</Link><FavoriteButton professional={{slug:item.slug,name:item.name,profession:item.profession,specialty:item.specialty,city:item.city,organization:item.organization,imageUrl:item.imageUrl}}/></div></article>})}</div>:null}
       {organizationResults.length>0&&!(type==="servicos"&&!q&&!category)?<div className="gss-list">{visibleOrganizations.map(item=>{const address=publicAddress(item.address);const phone=(item.phone??"").replace(/\D/g,"");const directions=item.mapUrl||(address?`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${address}, Piumhi - MG`)}`:"");return <article className="gss-card gss-card-biz" key={item.slug}><div className="gss-card-photo gss-card-logo" style={{backgroundImage:`url(${item.logoUrl||"/placeholders/company-logo.svg"})`}}/><div className="gss-card-body"><div className="gss-card-kicker"><span>{item.category}</span></div><h3>{item.name}</h3>{item.services.length?<p>{item.services.slice(0,3).join(" · ")}</p>:null}<div className="gss-card-pills">{address?<span><MapPin size={13}/> {address}</span>:null}</div></div><div className="gss-card-actions">{phone.length>=10?<a className="gss-a-primary" href={`tel:+55${phone}`}><Phone size={18}/> Ligar</a>:null}{directions?<a className="gss-a-see" href={directions} target="_blank" rel="noreferrer"><Navigation size={16}/> Como chegar</a>:null}<Link className="gss-a-see" href={`/empresas/${item.slug}`}>Ver detalhes</Link></div></article>})}</div>:null}
       <div className="gss-inclusion"><p>Não encontrou o que procura?</p><Link href="/inclusao?tipo=professional">Solicitar inclusão <ArrowUpRight size={15}/></Link></div>
     </div>
   </div>
 </div></div>;
 return <main className={`native-search-screen${isLanding?" native-search-landing":" native-search-results"}`}>{desktop}<div className="native-search-aura" aria-hidden="true"/><div className="native-search-shell">
  <header className="native-search-header"><Link className="native-search-back" href="/" aria-label="Voltar"><ArrowLeft size={20}/></Link><div className="native-search-title"><h1>Buscar</h1><p>Encontre profissionais, clínicas, exames e muito mais.</p></div></header>
  <form className="native-search-form" action="/buscar" role="search"><Search size={19}/><input name="q" defaultValue={q} autoComplete="off" enterKeyHint="search" aria-label="O que você está buscando?" placeholder="O que você está buscando?"/><input type="hidden" name="cidade" value="piumhi"/><button type="submit" aria-label="Buscar"><Search size={19}/></button></form>
  <nav className="native-search-tabs native-search-tabs-scroll" aria-label="Modalidade de busca"><Link href="/buscar?cidade=piumhi" className={type==="todos"?"active":""}>Todos</Link><Link href="/buscar?cidade=piumhi&tipo=professionals" className={type==="profissionais"?"active":""}>Profissionais</Link><Link href="/buscar?cidade=piumhi&tipo=services" className={clinicsActive?"active":""}>Clínicas</Link><Link href="/buscar?categoria=farmacias&cidade=piumhi&tipo=services" className={pharmacyActive?"active":""}>Farmácias</Link><Link href="/buscar?q=exames&cidade=piumhi&tipo=services" className={examsActive?"active":""}>Exames</Link></nav>
  {isLanding?<section className="native-search-discovery"><div className="native-section-head native-specialties-head"><h2>Especialidades</h2><button type="button" className="native-refine-trigger" onClick={()=>setRefineOpen(true)}><SlidersHorizontal size={15}/> Refinar busca</button></div><div className="native-specialty-grid native-specialty-grid-expanded">{quickSpecialties.map(({label,query,Icon},index)=><Link key={label} className={`native-specialty-card tone-${index+1}`} href={query?`/buscar?q=${encodeURIComponent(query)}&cidade=piumhi&tipo=professionals`:"/buscar/especialidades"}><span><Icon size={25} strokeWidth={1.65}/></span><strong>{label}</strong></Link>)}</div></section>:<div className="search-desk-layout"><aside className="search-desk-aside" aria-label="Filtros"><form action="/buscar"><input type="hidden" name="cidade" value="piumhi"/>{typeParam?<input type="hidden" name="tipo" value={typeParam}/>:null}<h2><SlidersHorizontal size={17}/> Filtros</h2><label>Buscar<input name="q" defaultValue={q} placeholder="Nome ou especialidade"/></label>{type!=="servicos"?<><label>Profissão<select name="profissao" defaultValue={profession}><option value="">Todas</option>{professions.map(i=><option key={i}>{i}</option>)}</select></label><label>Especialidade<select name="especialidade" defaultValue={specialty}><option value="">Todas</option>{specialtyChoices.map(i=><option key={i}>{i}</option>)}</select></label></>:null}{type!=="profissionais"?<label>Tipo de serviço<select name="categoria" defaultValue={category}><option value="">Todos</option>{categoryChoices.map(i=><option key={i.key} value={i.key}>{i.label}</option>)}</select></label>:null}<button type="submit">Aplicar filtros</button>{(q||profession||specialty||category)?<Link className="sda-clear" href="/buscar?cidade=piumhi">Limpar filtros</Link>:null}</form></aside><div className="search-desk-main">
   <section className="native-results-toolbar"><div><span>{type==="profissionais"?professionalResults.length:type==="servicos"?organizationResults.length:total}</span><p>{type==="profissionais"?"profissionais encontrados":type==="servicos"?"serviços encontrados":"resultados encontrados"}</p></div><details className="native-filter-sheet"><summary><SlidersHorizontal size={16}/> Filtros</summary><div className="native-filter-backdrop"/><div className="native-filter-panel"><div className="native-filter-heading"><div><small>Refine sua busca</small><h2>Filtros</h2></div><span><X size={18}/></span></div><form action="/buscar"><input type="hidden" name="cidade" value="piumhi"/><label>Buscar<input name="q" defaultValue={q} placeholder="Nome ou especialidade"/></label>{type!=="servicos"?<><label>Profissão<select name="profissao" defaultValue={profession}><option value="">Todas</option>{professions.map(i=><option key={i}>{i}</option>)}</select></label><label>Especialidade<select name="especialidade" defaultValue={specialty}><option value="">Todas</option>{specialtyChoices.map(i=><option key={i}>{i}</option>)}</select></label></>:null}{type!=="profissionais"?<label>Tipo de serviço<select name="categoria" defaultValue={category}><option value="">Todos</option>{categoryChoices.map(i=><option key={i.key} value={i.key}>{i.label}</option>)}</select></label>:null}<button type="submit">Aplicar filtros</button></form></div></details></section>
   {(q||profession||specialty||category)?<div className="native-active-filters">{q?<Link href={clearFilter("q")}>{q}<X size={11}/></Link>:null}{profession?<Link href={clearFilter("profissao")}>{profession}<X size={11}/></Link>:null}{specialty?<Link href={clearFilter("especialidade")}>{specialty}<X size={11}/></Link>:null}{category?<Link href={clearFilter("categoria")}>{category}<X size={11}/></Link>:null}</div>:null}
   {type==="servicos"&&!q&&!category?<section className="native-category-picker"><div className="native-section-head"><h2>O que você procura?</h2><span>Escolha uma categoria</span></div><div className="native-category-grid">{categoryChoices.map(i=><Link key={i.key} href={`/buscar?categoria=${encodeURIComponent(i.key)}&cidade=piumhi&tipo=services`}><span><Building2 size={19}/></span><strong>{i.label}</strong><small>{i.count}</small></Link>)}</div></section>:null}
   {total===0?<section className="native-empty-state"><span><Search size={24}/></span><h2>Nada encontrado</h2><p>Tente outro termo ou remova alguns filtros.</p><Link href="/buscar?cidade=piumhi">Limpar busca</Link></section>:null}
   {professionalResults.length>0?<section className="native-result-section">{type==="todos"?<div className="native-section-head"><h2>Profissionais</h2></div>:null}<div className="native-professional-list">{visibleProfessionals.map((item,index)=>{const contact=item.featured?directContact(item.whatsapp,item.phone):null;return <article className={`native-professional-card${item.featured?" featured":""}`} key={item.slug}>{item.featured?<span className="native-featured"><Sparkles size={11}/> Destaque</span>:null}<div className={`native-professional-avatar${item.imageUrl?" has-photo":""}`}>{item.imageUrl?<ProfessionalImage src={item.imageUrl} sizes="72px" eager={index<2}/>:<ProfessionIcon profession={item.profession}/>}</div><div className="native-professional-copy"><div className="native-card-name"><div><small>{professionLabel(item)}</small><h2>{item.name}</h2></div><FavoriteButton professional={{slug:item.slug,name:item.name,profession:item.profession,specialty:item.specialty,city:item.city,organization:item.organization,imageUrl:item.imageUrl}} compact/></div>{item.specialty?<div className="native-card-tags"><span>{item.specialty}</span></div>:null}{item.organization?<p>{item.organization}</p>:null}</div><div className="native-card-actions">{contact?<a className="primary" href={contact.href}><Phone size={14}/> {contact.label}</a>:null}<Link className={contact?"":"primary"} href={`/profissionais/${item.slug}`}>Ver perfil <ArrowUpRight size={14}/></Link></div></article>})}</div></section>:null}
   {organizationResults.length>0&&!(type==="servicos"&&!q&&!category)?<section className="native-result-section"><div className="native-business-list">{visibleOrganizations.map(item=><article className="native-business-card" key={item.slug}><div className="native-business-logo" style={{backgroundImage:`url(${item.logoUrl||"/placeholders/company-logo.svg"})`}}/><div className="native-business-copy"><small>{item.category}</small><h2>{item.name}</h2>{publicAddress(item.address)?<p>{publicAddress(item.address)}</p>:null}{item.services.length?<p>{item.services.slice(0,2).join(" · ")}</p>:null}</div><div className="native-card-actions"><Link className="primary" href={`/empresas/${item.slug}`}>Ver detalhes <ArrowUpRight size={14}/></Link></div></article>)}</div></section>:null}
  </div></div>}
 </div>
 {refineOpen?<div className="native-refine-overlay" role="presentation" onMouseDown={e=>{if(e.currentTarget===e.target)setRefineOpen(false)}}><section className="native-refine-sheet" role="dialog" aria-modal="true" aria-labelledby="refine-title"><div className="native-refine-handle"/><header><div><small>BUSCA ESPECÍFICA</small><h2 id="refine-title">Refinar profissionais</h2><p>Combine profissão e especialidade para chegar mais rápido ao profissional certo.</p></div><button type="button" onClick={()=>setRefineOpen(false)} aria-label="Fechar"><X size={19}/></button></header><form onSubmit={submitRefine}><label>Nome do profissional<input name="q" value={refineName} onChange={e=>setRefineName(e.target.value)} placeholder="Ex.: Paulo, Jaíne..." autoComplete="off"/></label><label>Profissão<select name="profissao" value={refineProfession} onChange={e=>{setRefineProfession(e.target.value);setRefineSpecialty("")}}><option value="">Todas as profissões</option>{professions.map(i=><option key={i} value={i}>{i}</option>)}</select></label><label>Especialidade<select name="especialidade" value={effectiveRefineSpecialty} onChange={e=>setRefineSpecialty(e.target.value)}><option value="">Todas as especialidades</option>{refineSpecialties.map(i=><option key={i} value={i}>{i}</option>)}</select></label><button className="native-refine-submit" type="submit">VER PROFISSIONAIS <ChevronRight size={17}/></button></form><button className="native-refine-clear" type="button" onClick={()=>{setRefineName("");setRefineProfession("");setRefineSpecialty("")}}>Limpar seleção</button></section></div>:null}
 </main>
}
export default function SearchPage(){return <Suspense fallback={<main className="native-search-screen"><div className="native-search-loading">Carregando busca…</div></main>}><SearchDirectory/></Suspense>}
